// Generated by nexgen latest. DO NOT EDIT!

import type { TransferTypeConverter } from "nexus-rpc";
import { createPayloadValidationError } from "@temporalio/common";
import * as __nexgenDefinitions from "./definitions";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

/**
 * One append call: who is writing, where, and what.
 */
export interface AppendInput {
  /**
   * The workflow whose stream is being written.
   */
  workflowId: string;
  /**
   * The named stream to append to.
   */
  stream: string;
  /**
   * Identifies the writer across its retries, so its attempts can be ordered.
   */
  producerId: string;
  /**
   * The generation this producer is writing. A later attempt supersedes an earlier one.
   */
  attempt: number;
  /**
   * Counts this producer's batches from 1. The handler drops an index it has already
   * written for this producer attempt.
   */
  batchIndex: number;
  /**
   * The records to write. Empty on a call that only finishes the producer.
   */
  payloads?: Uint8Array[];
  /**
   * Mark this producer done after writing the batch, so a reader stops waiting on it.
   */
  finish?: boolean;
}

/**
 * Where the append landed, empty when it wrote nothing.
 */
export interface AppendOutput {
  /**
   * Names the last record written by this call. Empty when the call carried no
   * payloads.
   */
  cursor?: string;
}

/**
 * One read call: where to resume from and how long to wait.
 */
export interface ReadInput {
  /**
   * The workflow whose stream is being read.
   */
  workflowId: string;
  /**
   * The named stream to read. Empty reads every stream the workflow publishes.
   */
  stream?: string;
  /**
   * A token from an earlier record or append. Empty starts at the beginning.
   */
  afterToken?: string;
  /**
   * Return at most this many records. Defaults to 100.
   */
  maxRecords?: number;
  /**
   * Wait at most this long for records to arrive before answering. Defaults to 5000. A
   * call that collects nothing answers with no records and the caller's own token.
   */
  waitMs?: number;
}

/**
 * What one read call answered, and where to resume.
 */
export interface ReadOutput {
  /**
   * The records after the caller's token, in stream order.
   */
  records?: RecordWire[];
  /**
   * Pass as afterToken on the following call. Echoes the caller's own token when the
   * call collected nothing.
   */
  nextToken?: string;
}

/**
 * One record on the wire: its cursor and its frame.
 */
export interface RecordWire {
  /**
   * Names this record. Pass it as afterToken to resume just past it.
   */
  token: string;
  /**
   * The record frame, carrying the topic, kind, producer, attempt, sequence and body.
   */
  frame: Uint8Array;
}

export const appendInputTransferTypeConverter =
  new (class implements TransferTypeConverter<AppendInput> {
    public fromTransferType(raw: unknown): AppendInput {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let workflowId: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "workflowId") ||
        raw["workflowId"] === null
      ) {
        violations.push({ path: "workflowId", reason: "required" });
      } else {
        if (typeof raw["workflowId"] !== "string") {
          violations.push({ path: "workflowId", reason: "expected string" });
        } else {
          workflowId = raw["workflowId"];
        }
      }

      let stream: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "stream") ||
        raw["stream"] === null
      ) {
        violations.push({ path: "stream", reason: "required" });
      } else {
        if (typeof raw["stream"] !== "string") {
          violations.push({ path: "stream", reason: "expected string" });
        } else {
          stream = raw["stream"];
        }
      }

      let producerId: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "producerId") ||
        raw["producerId"] === null
      ) {
        violations.push({ path: "producerId", reason: "required" });
      } else {
        if (typeof raw["producerId"] !== "string") {
          violations.push({ path: "producerId", reason: "expected string" });
        } else {
          producerId = raw["producerId"];
        }
      }

      let attempt: number = undefined as unknown as number;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "attempt") ||
        raw["attempt"] === null
      ) {
        violations.push({ path: "attempt", reason: "required" });
      } else {
        if (
          typeof raw["attempt"] !== "number" ||
          !Number.isSafeInteger(raw["attempt"])
        ) {
          violations.push({ path: "attempt", reason: "expected integer" });
        } else {
          attempt = raw["attempt"];
          if (raw["attempt"] < 1) {
            violations.push({
              path: "attempt",
              reason: `must be >= 1, got ${raw["attempt"]}`,
            });
          }
        }
      }

      let batchIndex: number = undefined as unknown as number;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "batchIndex") ||
        raw["batchIndex"] === null
      ) {
        violations.push({ path: "batchIndex", reason: "required" });
      } else {
        if (
          typeof raw["batchIndex"] !== "number" ||
          !Number.isSafeInteger(raw["batchIndex"])
        ) {
          violations.push({ path: "batchIndex", reason: "expected integer" });
        } else {
          batchIndex = raw["batchIndex"];
          if (raw["batchIndex"] < 1) {
            violations.push({
              path: "batchIndex",
              reason: `must be >= 1, got ${raw["batchIndex"]}`,
            });
          }
        }
      }

      let payloads: Uint8Array[] | undefined = undefined as unknown as
        | Uint8Array[]
        | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "payloads") &&
        raw["payloads"] === null
      ) {
        violations.push({ path: "payloads", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "payloads")) {
        if (!Array.isArray(raw["payloads"])) {
          violations.push({ path: "payloads", reason: "expected array" });
        } else {
          payloads = [];
          raw["payloads"].forEach((element: unknown, index: number) => {
            let item: Uint8Array = undefined as unknown as Uint8Array;
            if (typeof element !== "string") {
              violations.push({
                path: `payloads[${index}]`,
                reason: "expected string",
              });
            } else {
              const parsed = __nexgenDefinitions.base64ToBytes(
                element,
                `payloads[${index}]`,
                violations,
              );
              if (parsed !== undefined) {
                item = parsed;
              }
            }
            if (item !== undefined) {
              payloads!.push(item);
            }
          });
        }
      }

      let finish: boolean | undefined = undefined as unknown as boolean | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "finish") &&
        raw["finish"] === null
      ) {
        violations.push({ path: "finish", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "finish")) {
        if (typeof raw["finish"] !== "boolean") {
          violations.push({ path: "finish", reason: "expected boolean" });
        } else {
          finish = raw["finish"];
        }
      }

      for (const key of Object.keys(raw)) {
        if (
          key !== "workflowId" &&
          key !== "stream" &&
          key !== "producerId" &&
          key !== "attempt" &&
          key !== "batchIndex" &&
          key !== "payloads" &&
          key !== "finish"
        ) {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: AppendInput = { workflowId, stream, producerId, attempt, batchIndex };
      if (payloads !== undefined) {
        out.payloads = payloads;
      }
      if (finish !== undefined) {
        out.finish = finish;
      }
      return out;
    }

    public toTransferType(value: AppendInput): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.workflowId === undefined || value.workflowId === null) {
        violations.push({ path: "workflowId", reason: "required" });
      } else {
        if (!(typeof value.workflowId === "string")) {
          violations.push({ path: "workflowId", reason: "expected string" });
        }
        out["workflowId"] = value.workflowId;
      }
      if (value.stream === undefined || value.stream === null) {
        violations.push({ path: "stream", reason: "required" });
      } else {
        if (!(typeof value.stream === "string")) {
          violations.push({ path: "stream", reason: "expected string" });
        }
        out["stream"] = value.stream;
      }
      if (value.producerId === undefined || value.producerId === null) {
        violations.push({ path: "producerId", reason: "required" });
      } else {
        if (!(typeof value.producerId === "string")) {
          violations.push({ path: "producerId", reason: "expected string" });
        }
        out["producerId"] = value.producerId;
      }
      if (value.attempt === undefined || value.attempt === null) {
        violations.push({ path: "attempt", reason: "required" });
      } else {
        if (!(typeof value.attempt === "number" && Number.isInteger(value.attempt))) {
          violations.push({ path: "attempt", reason: "expected integer" });
        } else {
          if (!Number.isSafeInteger(value.attempt)) {
            violations.push({
              path: "attempt",
              reason: "exceeds ±(2^53-1) integer cap",
            });
          } else {
            if (value.attempt < 1) {
              violations.push({
                path: "attempt",
                reason: `must be >= 1, got ${value.attempt}`,
              });
            }
          }
        }
        out["attempt"] = value.attempt;
      }
      if (value.batchIndex === undefined || value.batchIndex === null) {
        violations.push({ path: "batchIndex", reason: "required" });
      } else {
        if (
          !(typeof value.batchIndex === "number" && Number.isInteger(value.batchIndex))
        ) {
          violations.push({ path: "batchIndex", reason: "expected integer" });
        } else {
          if (!Number.isSafeInteger(value.batchIndex)) {
            violations.push({
              path: "batchIndex",
              reason: "exceeds ±(2^53-1) integer cap",
            });
          } else {
            if (value.batchIndex < 1) {
              violations.push({
                path: "batchIndex",
                reason: `must be >= 1, got ${value.batchIndex}`,
              });
            }
          }
        }
        out["batchIndex"] = value.batchIndex;
      }
      if (value.payloads !== undefined) {
        if (value.payloads === null) {
          violations.push({ path: "payloads", reason: "explicit null not allowed" });
        } else {
          const payloadsViolationCount = violations.length;
          if (!Array.isArray(value.payloads)) {
            violations.push({ path: "payloads", reason: "expected array" });
          } else {
            value.payloads.forEach((element, index) => {
              if (!(element instanceof Uint8Array)) {
                violations.push({
                  path: `payloads[${index}]`,
                  reason: "expected bytes",
                });
              }
            });
          }
          if (violations.length === payloadsViolationCount) {
            out["payloads"] = value.payloads.map((element, index) =>
              __nexgenDefinitions.bytesToBase64(element),
            );
          }
        }
      }
      if (value.finish !== undefined) {
        if (value.finish === null) {
          violations.push({ path: "finish", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.finish === "boolean")) {
            violations.push({ path: "finish", reason: "expected boolean" });
          }
          out["finish"] = value.finish;
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();

export const appendOutputTransferTypeConverter =
  new (class implements TransferTypeConverter<AppendOutput> {
    public fromTransferType(raw: unknown): AppendOutput {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let cursor: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "cursor") &&
        raw["cursor"] === null
      ) {
        violations.push({ path: "cursor", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "cursor")) {
        if (typeof raw["cursor"] !== "string") {
          violations.push({ path: "cursor", reason: "expected string" });
        } else {
          cursor = raw["cursor"];
        }
      }

      for (const key of Object.keys(raw)) {
        if (key !== "cursor") {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: AppendOutput = {};
      if (cursor !== undefined) {
        out.cursor = cursor;
      }
      return out;
    }

    public toTransferType(value: AppendOutput): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.cursor !== undefined) {
        if (value.cursor === null) {
          violations.push({ path: "cursor", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.cursor === "string")) {
            violations.push({ path: "cursor", reason: "expected string" });
          }
          out["cursor"] = value.cursor;
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();

export const readInputTransferTypeConverter =
  new (class implements TransferTypeConverter<ReadInput> {
    public fromTransferType(raw: unknown): ReadInput {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let workflowId: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "workflowId") ||
        raw["workflowId"] === null
      ) {
        violations.push({ path: "workflowId", reason: "required" });
      } else {
        if (typeof raw["workflowId"] !== "string") {
          violations.push({ path: "workflowId", reason: "expected string" });
        } else {
          workflowId = raw["workflowId"];
        }
      }

      let stream: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "stream") &&
        raw["stream"] === null
      ) {
        violations.push({ path: "stream", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "stream")) {
        if (typeof raw["stream"] !== "string") {
          violations.push({ path: "stream", reason: "expected string" });
        } else {
          stream = raw["stream"];
        }
      }

      let afterToken: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "afterToken") &&
        raw["afterToken"] === null
      ) {
        violations.push({ path: "afterToken", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "afterToken")) {
        if (typeof raw["afterToken"] !== "string") {
          violations.push({ path: "afterToken", reason: "expected string" });
        } else {
          afterToken = raw["afterToken"];
        }
      }

      let maxRecords: number | undefined = undefined as unknown as number | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "maxRecords") &&
        raw["maxRecords"] === null
      ) {
        violations.push({ path: "maxRecords", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "maxRecords")) {
        if (
          typeof raw["maxRecords"] !== "number" ||
          !Number.isSafeInteger(raw["maxRecords"])
        ) {
          violations.push({ path: "maxRecords", reason: "expected integer" });
        } else {
          maxRecords = raw["maxRecords"];
          if (raw["maxRecords"] < 1) {
            violations.push({
              path: "maxRecords",
              reason: `must be >= 1, got ${raw["maxRecords"]}`,
            });
          }
        }
      }

      let waitMs: number | undefined = undefined as unknown as number | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "waitMs") &&
        raw["waitMs"] === null
      ) {
        violations.push({ path: "waitMs", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "waitMs")) {
        if (typeof raw["waitMs"] !== "number" || !Number.isSafeInteger(raw["waitMs"])) {
          violations.push({ path: "waitMs", reason: "expected integer" });
        } else {
          waitMs = raw["waitMs"];
          if (raw["waitMs"] < 0) {
            violations.push({
              path: "waitMs",
              reason: `must be >= 0, got ${raw["waitMs"]}`,
            });
          }
        }
      }

      for (const key of Object.keys(raw)) {
        if (
          key !== "workflowId" &&
          key !== "stream" &&
          key !== "afterToken" &&
          key !== "maxRecords" &&
          key !== "waitMs"
        ) {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: ReadInput = { workflowId };
      if (stream !== undefined) {
        out.stream = stream;
      }
      if (afterToken !== undefined) {
        out.afterToken = afterToken;
      }
      if (maxRecords !== undefined) {
        out.maxRecords = maxRecords;
      }
      if (waitMs !== undefined) {
        out.waitMs = waitMs;
      }
      return out;
    }

    public toTransferType(value: ReadInput): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.workflowId === undefined || value.workflowId === null) {
        violations.push({ path: "workflowId", reason: "required" });
      } else {
        if (!(typeof value.workflowId === "string")) {
          violations.push({ path: "workflowId", reason: "expected string" });
        }
        out["workflowId"] = value.workflowId;
      }
      if (value.stream !== undefined) {
        if (value.stream === null) {
          violations.push({ path: "stream", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.stream === "string")) {
            violations.push({ path: "stream", reason: "expected string" });
          }
          out["stream"] = value.stream;
        }
      }
      if (value.afterToken !== undefined) {
        if (value.afterToken === null) {
          violations.push({ path: "afterToken", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.afterToken === "string")) {
            violations.push({ path: "afterToken", reason: "expected string" });
          }
          out["afterToken"] = value.afterToken;
        }
      }
      if (value.maxRecords !== undefined) {
        if (value.maxRecords === null) {
          violations.push({ path: "maxRecords", reason: "explicit null not allowed" });
        } else {
          if (
            !(
              typeof value.maxRecords === "number" && Number.isInteger(value.maxRecords)
            )
          ) {
            violations.push({ path: "maxRecords", reason: "expected integer" });
          } else {
            if (!Number.isSafeInteger(value.maxRecords)) {
              violations.push({
                path: "maxRecords",
                reason: "exceeds ±(2^53-1) integer cap",
              });
            } else {
              if (value.maxRecords < 1) {
                violations.push({
                  path: "maxRecords",
                  reason: `must be >= 1, got ${value.maxRecords}`,
                });
              }
            }
          }
          out["maxRecords"] = value.maxRecords;
        }
      }
      if (value.waitMs !== undefined) {
        if (value.waitMs === null) {
          violations.push({ path: "waitMs", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.waitMs === "number" && Number.isInteger(value.waitMs))) {
            violations.push({ path: "waitMs", reason: "expected integer" });
          } else {
            if (!Number.isSafeInteger(value.waitMs)) {
              violations.push({
                path: "waitMs",
                reason: "exceeds ±(2^53-1) integer cap",
              });
            } else {
              if (value.waitMs < 0) {
                violations.push({
                  path: "waitMs",
                  reason: `must be >= 0, got ${value.waitMs}`,
                });
              }
            }
          }
          out["waitMs"] = value.waitMs;
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();

export const readOutputTransferTypeConverter =
  new (class implements TransferTypeConverter<ReadOutput> {
    public fromTransferType(raw: unknown): ReadOutput {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let records: RecordWire[] | undefined = undefined as unknown as
        | RecordWire[]
        | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "records") &&
        raw["records"] === null
      ) {
        violations.push({ path: "records", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "records")) {
        if (!Array.isArray(raw["records"])) {
          violations.push({ path: "records", reason: "expected array" });
        } else {
          records = [];
          raw["records"].forEach((element: unknown, index: number) => {
            let item: RecordWire = undefined as unknown as RecordWire;
            try {
              item = recordWireTransferTypeConverter.fromTransferType(element);
            } catch (error) {
              __nexgenDefinitions.collect(violations, `records[${index}]`, error);
            }
            if (item !== undefined) {
              records!.push(item);
            }
          });
        }
      }

      let nextToken: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "nextToken") &&
        raw["nextToken"] === null
      ) {
        violations.push({ path: "nextToken", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "nextToken")) {
        if (typeof raw["nextToken"] !== "string") {
          violations.push({ path: "nextToken", reason: "expected string" });
        } else {
          nextToken = raw["nextToken"];
        }
      }

      for (const key of Object.keys(raw)) {
        if (key !== "records" && key !== "nextToken") {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: ReadOutput = {};
      if (records !== undefined) {
        out.records = records;
      }
      if (nextToken !== undefined) {
        out.nextToken = nextToken;
      }
      return out;
    }

    public toTransferType(value: ReadOutput): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.records !== undefined) {
        if (value.records === null) {
          violations.push({ path: "records", reason: "explicit null not allowed" });
        } else {
          const recordsViolationCount = violations.length;
          if (!Array.isArray(value.records)) {
            violations.push({ path: "records", reason: "expected array" });
          } else {
            value.records.forEach((element, index) => {});
          }
          if (violations.length === recordsViolationCount) {
            out["records"] = value.records.map((element, index) =>
              (() => {
                try {
                  return recordWireTransferTypeConverter.toTransferType(element);
                } catch (error) {
                  __nexgenDefinitions.collect(violations, `records[${index}]`, error);
                  return undefined;
                }
              })(),
            );
          }
        }
      }
      if (value.nextToken !== undefined) {
        if (value.nextToken === null) {
          violations.push({ path: "nextToken", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.nextToken === "string")) {
            violations.push({ path: "nextToken", reason: "expected string" });
          }
          out["nextToken"] = value.nextToken;
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();

export const recordWireTransferTypeConverter =
  new (class implements TransferTypeConverter<RecordWire> {
    public fromTransferType(raw: unknown): RecordWire {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let token: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "token") ||
        raw["token"] === null
      ) {
        violations.push({ path: "token", reason: "required" });
      } else {
        if (typeof raw["token"] !== "string") {
          violations.push({ path: "token", reason: "expected string" });
        } else {
          token = raw["token"];
        }
      }

      let frame: Uint8Array = undefined as unknown as Uint8Array;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "frame") ||
        raw["frame"] === null
      ) {
        violations.push({ path: "frame", reason: "required" });
      } else {
        if (typeof raw["frame"] !== "string") {
          violations.push({ path: "frame", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.base64ToBytes(
            raw["frame"],
            "frame",
            violations,
          );
          if (parsed !== undefined) {
            frame = parsed;
          }
        }
      }

      for (const key of Object.keys(raw)) {
        if (key !== "token" && key !== "frame") {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: RecordWire = { token, frame };
      return out;
    }

    public toTransferType(value: RecordWire): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.token === undefined || value.token === null) {
        violations.push({ path: "token", reason: "required" });
      } else {
        if (!(typeof value.token === "string")) {
          violations.push({ path: "token", reason: "expected string" });
        }
        out["token"] = value.token;
      }
      if (value.frame === undefined || value.frame === null) {
        violations.push({ path: "frame", reason: "required" });
      } else {
        const frameViolationCount = violations.length;
        if (!(value.frame instanceof Uint8Array)) {
          violations.push({ path: "frame", reason: "expected bytes" });
        }
        if (violations.length === frameViolationCount) {
          out["frame"] = __nexgenDefinitions.bytesToBase64(value.frame);
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();
