# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

import temporalio.workflow

from ..models import (
    Request,
    Response,
)


async def _first_operation(
    request: Request,
) -> temporalio.workflow.NexusOperationHandle[Response,]:
    nexus_client = temporalio.workflow.create_nexus_client(
        service="InterceptorService",
        endpoint="__temporal_system",
    )
    return await nexus_client.start_operation(
        operation="FirstOperation",
        input=request,
        output_type=Response,
    )


async def first_operation(
    *,
    id: str,
) -> temporalio.workflow.NexusOperationHandle[Response,]:
    request = Request(
        id=id,
    )
    return await _first_operation(request)
