// Code generated by nexgen latest. DO NOT EDIT.

package streams

import (
	"encoding/json"
	"fmt"

	"github.com/nexus-rpc/sdk-go/nexus"
)

// Append records to a workflow's stream and read them back. Reads hand out batches and
// an append carries one batch per call, because a call per record costs too much for a
// token stream.
var StreamService = struct {
	ServiceName string
	// Append one batch of records. A repeated batchIndex for the same producer attempt is
	// dropped, so a retried call writes once.
	Append nexus.OperationReference[AppendInput, AppendOutput]
	// Answer with the records after the caller's token, or time out. The call parks until
	// it has maxRecords records or waitMs elapses, whichever comes first, and answers with
	// whatever it collected.
	Read nexus.OperationReference[ReadInput, ReadOutput]
}{
	ServiceName: "example.streams.v1.StreamService",
	Append:      nexus.NewOperationReference[AppendInput, AppendOutput]("append"),
	Read:        nexus.NewOperationReference[ReadInput, ReadOutput]("read"),
}

// AppendInput One append call: who is writing, where, and what.
type AppendInput struct {
	// WorkflowID The workflow whose stream is being written.
	WorkflowID string `json:"workflowId"`
	// Stream The named stream to append to.
	Stream string `json:"stream"`
	// ProducerID Identifies the writer across its retries, so its attempts can be ordered.
	ProducerID string `json:"producerId"`
	// Attempt The generation this producer is writing. A later attempt supersedes an
	// earlier one.
	Attempt int64 `json:"attempt"`
	// BatchIndex Counts this producer's batches from 1. The handler drops an index it has
	// already written for this producer attempt.
	BatchIndex int64 `json:"batchIndex"`
	// Payloads The records to write. Empty on a call that only finishes the producer.
	Payloads [][]byte `json:"payloads,omitempty"`
	// Finish Mark this producer done after writing the batch, so a reader stops waiting on
	// it.
	Finish *bool `json:"finish,omitempty"`
}

// Validate checks m against every constraint and returns a PayloadValidationError
// listing any violations.
func (m AppendInput) Validate() error {
	var errs []Violation
	if m.Attempt < -integerCap || m.Attempt > integerCap {
		errs = append(errs, Violation{"attempt", "exceeds ±(2^53-1) integer cap"})
	}
	if m.Attempt < 1 {
		errs = append(errs, Violation{"attempt", fmt.Sprintf("must be >= 1, got %v", m.Attempt)})
	}
	if m.BatchIndex < -integerCap || m.BatchIndex > integerCap {
		errs = append(errs, Violation{"batchIndex", "exceeds ±(2^53-1) integer cap"})
	}
	if m.BatchIndex < 1 {
		errs = append(errs, Violation{"batchIndex", fmt.Sprintf("must be >= 1, got %v", m.BatchIndex)})
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// PayloadValidationError listing any violations.
func (m *AppendInput) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "workflowId", "stream", "producerId", "attempt", "batchIndex", "payloads", "finish":
		default:
			errs = append(errs, Violation{memberPath(k), "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("workflowId"), "workflowId", true, false, &errs); ok {
		m.WorkflowID = v
	}
	if v, ok := parseStringField(get("stream"), "stream", true, false, &errs); ok {
		m.Stream = v
	}
	if v, ok := parseStringField(get("producerId"), "producerId", true, false, &errs); ok {
		m.ProducerID = v
	}
	if v, ok := parseIntegerField(get("attempt"), "attempt", true, false, &errs); ok {
		if v < 1 {
			errs = append(errs, Violation{"attempt", fmt.Sprintf("must be >= 1, got %v", v)})
		}
		m.Attempt = v
	}
	if v, ok := parseIntegerField(get("batchIndex"), "batchIndex", true, false, &errs); ok {
		if v < 1 {
			errs = append(errs, Violation{"batchIndex", fmt.Sprintf("must be >= 1, got %v", v)})
		}
		m.BatchIndex = v
	}
	if raw := get("payloads"); raw == nil {
	} else if isNull(*raw) {
		errs = append(errs, Violation{"payloads", "explicit null not allowed"})
	} else {
		var elems0 []json.RawMessage
		if err := json.Unmarshal(*raw, &elems0); err != nil {
			errs = append(errs, Violation{"payloads", "expected array"})
		} else {
			m.Payloads = make([][]byte, 0, len(elems0))
			for i0, e0 := range elems0 {
				p0 := fmt.Sprintf("%s[%d]", "payloads", i0)
				if isNull(e0) {
					errs = append(errs, Violation{p0, "explicit null not allowed"})
					continue
				}
				if s0, ok := parseStringField(&e0, p0, true, false, &errs); ok {
					if value0, ok := decodeBase64(p0, s0, _nexgenJsonSchemaBase64ContentEncoding, &errs); ok {
						m.Payloads = append(m.Payloads, value0)
					}
				}
			}
		}
	}
	if v, ok := parseBoolField(get("finish"), "finish", false, false, &errs); ok {
		m.Finish = &v
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// PayloadValidationError if validation fails.
func (m AppendInput) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "workflowId", m.WorkflowID, &errs)
	marshalField(out, "stream", m.Stream, &errs)
	marshalField(out, "producerId", m.ProducerID, &errs)
	marshalField(out, "attempt", m.Attempt, &errs)
	marshalField(out, "batchIndex", m.BatchIndex, &errs)
	if m.Payloads != nil {
		wirePayloads0 := make([]any, 0, len(m.Payloads))
		for _, itemPayloads0 := range m.Payloads {
			wirePayloads0 = append(wirePayloads0, encodeBase64(itemPayloads0))
		}
		marshalField(out, "payloads", wirePayloads0, &errs)
	}
	if m.Finish != nil {
		marshalField(out, "finish", *m.Finish, &errs)
	}
	if len(errs) > 0 {
		return nil, newPayloadValidationError(errs)
	}
	return json.Marshal(out)
}

// AppendOutput Where the append landed, empty when it wrote nothing.
type AppendOutput struct {
	// Cursor Names the last record written by this call. Empty when the call carried no
	// payloads.
	Cursor *string `json:"cursor,omitempty"`
}

// Validate checks m against every constraint and returns a PayloadValidationError
// listing any violations.
func (m AppendOutput) Validate() error {
	var errs []Violation
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// PayloadValidationError listing any violations.
func (m *AppendOutput) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "cursor":
		default:
			errs = append(errs, Violation{memberPath(k), "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("cursor"), "cursor", false, false, &errs); ok {
		m.Cursor = &v
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// PayloadValidationError if validation fails.
func (m AppendOutput) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	if m.Cursor != nil {
		marshalField(out, "cursor", *m.Cursor, &errs)
	}
	if len(errs) > 0 {
		return nil, newPayloadValidationError(errs)
	}
	return json.Marshal(out)
}

// ReadInput One read call: where to resume from and how long to wait.
type ReadInput struct {
	// WorkflowID The workflow whose stream is being read.
	WorkflowID string `json:"workflowId"`
	// Stream The named stream to read. Empty reads every stream the workflow publishes.
	Stream *string `json:"stream,omitempty"`
	// AfterToken A token from an earlier record or append. Empty starts at the beginning.
	AfterToken *string `json:"afterToken,omitempty"`
	// MaxRecords Return at most this many records. Defaults to 100.
	MaxRecords *int64 `json:"maxRecords,omitempty"`
	// WaitMs Wait at most this long for records to arrive before answering. Defaults to
	// 5000. A call that collects nothing answers with no records and the caller's own
	// token.
	WaitMs *int64 `json:"waitMs,omitempty"`
}

// Validate checks m against every constraint and returns a PayloadValidationError
// listing any violations.
func (m ReadInput) Validate() error {
	var errs []Violation
	if m.MaxRecords != nil && (*m.MaxRecords < -integerCap || *m.MaxRecords > integerCap) {
		errs = append(errs, Violation{"maxRecords", "exceeds ±(2^53-1) integer cap"})
	}
	if m.MaxRecords != nil {
		if *m.MaxRecords < 1 {
			errs = append(errs, Violation{"maxRecords", fmt.Sprintf("must be >= 1, got %v", *m.MaxRecords)})
		}
	}
	if m.WaitMs != nil && (*m.WaitMs < -integerCap || *m.WaitMs > integerCap) {
		errs = append(errs, Violation{"waitMs", "exceeds ±(2^53-1) integer cap"})
	}
	if m.WaitMs != nil {
		if *m.WaitMs < 0 {
			errs = append(errs, Violation{"waitMs", fmt.Sprintf("must be >= 0, got %v", *m.WaitMs)})
		}
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// PayloadValidationError listing any violations.
func (m *ReadInput) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "workflowId", "stream", "afterToken", "maxRecords", "waitMs":
		default:
			errs = append(errs, Violation{memberPath(k), "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("workflowId"), "workflowId", true, false, &errs); ok {
		m.WorkflowID = v
	}
	if v, ok := parseStringField(get("stream"), "stream", false, false, &errs); ok {
		m.Stream = &v
	}
	if v, ok := parseStringField(get("afterToken"), "afterToken", false, false, &errs); ok {
		m.AfterToken = &v
	}
	if v, ok := parseIntegerField(get("maxRecords"), "maxRecords", false, false, &errs); ok {
		if v < 1 {
			errs = append(errs, Violation{"maxRecords", fmt.Sprintf("must be >= 1, got %v", v)})
		}
		m.MaxRecords = &v
	}
	if v, ok := parseIntegerField(get("waitMs"), "waitMs", false, false, &errs); ok {
		if v < 0 {
			errs = append(errs, Violation{"waitMs", fmt.Sprintf("must be >= 0, got %v", v)})
		}
		m.WaitMs = &v
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// PayloadValidationError if validation fails.
func (m ReadInput) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "workflowId", m.WorkflowID, &errs)
	if m.Stream != nil {
		marshalField(out, "stream", *m.Stream, &errs)
	}
	if m.AfterToken != nil {
		marshalField(out, "afterToken", *m.AfterToken, &errs)
	}
	if m.MaxRecords != nil {
		marshalField(out, "maxRecords", *m.MaxRecords, &errs)
	}
	if m.WaitMs != nil {
		marshalField(out, "waitMs", *m.WaitMs, &errs)
	}
	if len(errs) > 0 {
		return nil, newPayloadValidationError(errs)
	}
	return json.Marshal(out)
}

// ReadOutput What one read call answered, and where to resume.
type ReadOutput struct {
	// Records The records after the caller's token, in stream order.
	Records []RecordWire `json:"records,omitempty"`
	// NextToken Pass as afterToken on the following call. Echoes the caller's own token
	// when the call collected nothing.
	NextToken *string `json:"nextToken,omitempty"`
}

// Validate checks m against every constraint and returns a PayloadValidationError
// listing any violations.
func (m ReadOutput) Validate() error {
	var errs []Violation
	for i0, v0 := range m.Records {
		p0 := fmt.Sprintf("%s[%d]", "records", i0)
		mergeNested(&errs, p0, v0.Validate())
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// PayloadValidationError listing any violations.
func (m *ReadOutput) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "records", "nextToken":
		default:
			errs = append(errs, Violation{memberPath(k), "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if raw := get("records"); raw == nil {
	} else if isNull(*raw) {
		errs = append(errs, Violation{"records", "explicit null not allowed"})
	} else {
		var elems0 []json.RawMessage
		if err := json.Unmarshal(*raw, &elems0); err != nil {
			errs = append(errs, Violation{"records", "expected array"})
		} else {
			m.Records = make([]RecordWire, 0, len(elems0))
			for i0, e0 := range elems0 {
				p0 := fmt.Sprintf("%s[%d]", "records", i0)
				if isNull(e0) {
					errs = append(errs, Violation{p0, "explicit null not allowed"})
					continue
				}
				var value0 RecordWire
				if err := json.Unmarshal(e0, &value0); err != nil {
					mergeNested(&errs, p0, err)
				} else {
					m.Records = append(m.Records, value0)
				}
			}
		}
	}
	if v, ok := parseStringField(get("nextToken"), "nextToken", false, false, &errs); ok {
		m.NextToken = &v
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// PayloadValidationError if validation fails.
func (m ReadOutput) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	if m.Records != nil {
		marshalField(out, "records", m.Records, &errs)
	}
	if m.NextToken != nil {
		marshalField(out, "nextToken", *m.NextToken, &errs)
	}
	if len(errs) > 0 {
		return nil, newPayloadValidationError(errs)
	}
	return json.Marshal(out)
}

// RecordWire One record on the wire: its cursor and its frame.
type RecordWire struct {
	// Token Names this record. Pass it as afterToken to resume just past it.
	Token string `json:"token"`
	// Frame The record frame, carrying the topic, kind, producer, attempt, sequence and
	// body.
	Frame []byte `json:"frame"`
}

// Validate checks m against every constraint and returns a PayloadValidationError
// listing any violations.
func (m RecordWire) Validate() error {
	var errs []Violation
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// PayloadValidationError listing any violations.
func (m *RecordWire) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "token", "frame":
		default:
			errs = append(errs, Violation{memberPath(k), "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("token"), "token", true, false, &errs); ok {
		m.Token = v
	}
	if s, ok := parseStringField(get("frame"), "frame", true, false, &errs); ok {
		if v, ok := decodeBase64("frame", s, _nexgenJsonSchemaBase64ContentEncoding, &errs); ok {
			m.Frame = v
		}
	}
	if len(errs) > 0 {
		return newPayloadValidationError(errs)
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// PayloadValidationError if validation fails.
func (m RecordWire) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "token", m.Token, &errs)
	marshalField(out, "frame", encodeBase64(m.Frame), &errs)
	if len(errs) > 0 {
		return nil, newPayloadValidationError(errs)
	}
	return json.Marshal(out)
}
