# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service
from .models import (
    AppendInput,
    AppendOutput,
    ReadInput,
    ReadOutput,
)


@service(name="example.streams.v1.StreamService")
class StreamService:
    """Append records to a workflow's stream and read them back. Reads hand out batches and
    an append carries one batch per call, because a call per record costs too much for a
    token stream.
    """

    append: Operation[
        AppendInput,
        AppendOutput,
    ] = Operation(name="append")
    """Append one batch of records. A repeated batchIndex for the same producer attempt is
    dropped, so a retried call writes once.
    """

    read: Operation[
        ReadInput,
        ReadOutput,
    ] = Operation(name="read")
    """Answer with the records after the caller's token, or time out. The call parks until
    it has maxRecords records or waitMs elapses, whichever comes first, and answers with
    whatever it collected.
    """
