# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations


import abc
import typing

from . import models

if typing.TYPE_CHECKING:
    import temporalio.workflow
    from temporalio.worker._interceptor import StartNexusOperationInput


__all__ = [
    "_start_system_nexus_operation",
    "_SystemNexusWorkflowOutboundInterceptorBase",
    "_SystemNexusWorkflowOutboundInterceptorTerminal",
]


_InputT = typing.TypeVar("_InputT")
_OutputT = typing.TypeVar("_OutputT")


async def _start_system_nexus_operation(
    interceptor: _SystemNexusWorkflowOutboundInterceptorBase,
    input: StartNexusOperationInput[_InputT, _OutputT],
) -> temporalio.workflow.NexusOperationHandle[_OutputT]:
    if (
        input.service == "InterceptorService"
        and input.operation_name == "FirstOperation"
    ):
        typed_input = typing.cast(
            "StartNexusOperationInput[models.Request, models.Response]",
            input,
        )
        # The dispatch check above establishes that this operation's response type is _OutputT.
        return typing.cast(
            "temporalio.workflow.NexusOperationHandle[_OutputT]",
            await interceptor.start_first_operation(typed_input.input),
        )
    if (
        input.service == "InterceptorService"
        and input.operation_name == "SecondOperation"
    ):
        typed_input = typing.cast(
            "StartNexusOperationInput[models.Request, models.Response]",
            input,
        )
        # The dispatch check above establishes that this operation's response type is _OutputT.
        return typing.cast(
            "temporalio.workflow.NexusOperationHandle[_OutputT]",
            await interceptor.start_second_operation(typed_input.input),
        )
    raise ValueError(
        f"unsupported System Nexus operation: {input.service}/{input.operation_name}"
    )


class _SystemNexusWorkflowOutboundInterceptorBase(abc.ABC):
    @abc.abstractmethod
    def _next_system_nexus_interceptor(
        self,
    ) -> _SystemNexusWorkflowOutboundInterceptorBase: ...

    async def start_first_operation(
        self, request: models.Request
    ) -> temporalio.workflow.NexusOperationHandle[models.Response]:
        """Intercept the FirstOperation operation."""
        return await self._next_system_nexus_interceptor().start_first_operation(
            request
        )

    async def start_second_operation(
        self, request: models.Request
    ) -> temporalio.workflow.NexusOperationHandle[models.Response]:
        """Intercept the SecondOperation operation."""
        return await self._next_system_nexus_interceptor().start_second_operation(
            request
        )


class _SystemNexusWorkflowOutboundInterceptorTerminal(abc.ABC):
    @abc.abstractmethod
    async def _intercept_system_nexus_operation(
        self,
        input: StartNexusOperationInput[_InputT, _OutputT],
    ) -> temporalio.workflow.NexusOperationHandle[_OutputT]: ...

    async def start_first_operation(
        self, request: models.Request
    ) -> temporalio.workflow.NexusOperationHandle[models.Response]:
        from temporalio.worker._interceptor import StartNexusOperationInput
        from temporalio.nexus.system import TEMPORAL_SYSTEM_ENDPOINT
        from temporalio.workflow import NexusOperationCancellationType

        return await self._intercept_system_nexus_operation(
            StartNexusOperationInput(
                endpoint=TEMPORAL_SYSTEM_ENDPOINT,
                service="InterceptorService",
                operation="FirstOperation",
                input=request,
                output_type=models.Response,
                schedule_to_close_timeout=None,
                schedule_to_start_timeout=None,
                start_to_close_timeout=None,
                cancellation_type=NexusOperationCancellationType.WAIT_COMPLETED,
                headers=None,
                summary=None,
            )
        )

    async def start_second_operation(
        self, request: models.Request
    ) -> temporalio.workflow.NexusOperationHandle[models.Response]:
        from temporalio.worker._interceptor import StartNexusOperationInput
        from temporalio.nexus.system import TEMPORAL_SYSTEM_ENDPOINT
        from temporalio.workflow import NexusOperationCancellationType

        return await self._intercept_system_nexus_operation(
            StartNexusOperationInput(
                endpoint=TEMPORAL_SYSTEM_ENDPOINT,
                service="InterceptorService",
                operation="SecondOperation",
                input=request,
                output_type=models.Response,
                schedule_to_close_timeout=None,
                schedule_to_start_timeout=None,
                start_to_close_timeout=None,
                cancellation_type=NexusOperationCancellationType.WAIT_COMPLETED,
                headers=None,
                summary=None,
            )
        )
