# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

import dataclasses


@dataclasses.dataclass(slots=True)
class Request:
    id: str


@dataclasses.dataclass(slots=True)
class Response:
    value: str
