# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service
from .models import (
    Request,
    Response,
)


@service
class InterceptorService:
    first_operation: Operation[
        Request,
        Response,
    ] = Operation(name="FirstOperation")

    second_operation: Operation[
        Request,
        Response,
    ] = Operation(name="SecondOperation")
