# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

from ._definitions import Violation
import collections.abc
import typing

import nexusrpc
import temporalio.converter
from .services import StreamServiceClient
from . import services as _services

__all__ = [
    "Violation",
    "StreamServiceClient",
]


_InputT = typing.TypeVar("_InputT")
_OutputT = typing.TypeVar("_OutputT")


_SerializationContextFactory = collections.abc.Callable[
    [_InputT], temporalio.converter.SerializationContext
]


class _NexusOperationInfo(typing.Generic[_InputT, _OutputT]):
    def __init__(
        self,
        *,
        operation: nexusrpc.Operation[_InputT, _OutputT],
        serialization_context: _SerializationContextFactory[_InputT] | None = None,
    ) -> None:
        self.operation: nexusrpc.Operation[_InputT, _OutputT] = operation
        self.serialization_context: _SerializationContextFactory[_InputT] | None = (
            serialization_context
        )


__nexus_operation_registry__ = {
    (
        "example.streams.v1.StreamService",
        "append",
    ): _NexusOperationInfo(
        operation=_services.StreamService.append,
    ),
    (
        "example.streams.v1.StreamService",
        "read",
    ): _NexusOperationInfo(
        operation=_services.StreamService.read,
    ),
}
