# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

import asyncio
import base64
import collections.abc
import dataclasses
import json
import time
import typing
import urllib.error
import urllib.request

from .models import (
    AppendInput,
    AppendOutput,
    ReadInput,
    ReadOutput,
    _AppendInputTransferTypeConverter,
    _AppendOutputTransferTypeConverter,
    _ReadInputTransferTypeConverter,
    _ReadOutputTransferTypeConverter,
)


_PayloadSteps = tuple[str | None, ...]
"""One wire member chain from a model's root to a payload. `None` stands for
every element of the array reached so far.
"""


@typing.runtime_checkable
class PayloadCodec(typing.Protocol):
    """Transforms the payload bytes an operation carries.

    A caller applies it before the send and after the receive, so a payload
    never travels in the form the process holds it in. Both directions take and
    answer with a list of the same length, in order.
    """

    async def encode(self, payloads: list[bytes]) -> list[bytes]: ...

    async def decode(self, payloads: list[bytes]) -> list[bytes]: ...


class _Slot(typing.NamedTuple):
    container: typing.Any
    key: typing.Any


def _payload_slots(node: typing.Any, steps: _PayloadSteps) -> list[_Slot]:
    if not steps:
        return []
    head, rest = steps[0], steps[1:]
    if head is None:
        if not isinstance(node, list):
            return []
        entries = typing.cast("list[typing.Any]", node)
        if not rest:
            return [_Slot(entries, index) for index in range(len(entries))]
        return [slot for entry in entries for slot in _payload_slots(entry, rest)]
    if not isinstance(node, dict):
        return []
    members = typing.cast("dict[str, typing.Any]", node)
    if head not in members:
        return []
    if not rest:
        return [_Slot(members, head)]
    return _payload_slots(members[head], rest)


async def _apply_codec(
    wire: typing.Any,
    sites: tuple[_PayloadSteps, ...],
    transform: collections.abc.Callable[
        [list[bytes]], collections.abc.Awaitable[list[bytes]]
    ],
) -> None:
    """Runs every payload the sites reach through the codec, in one call.

    The codec sees one list per request, so whatever it does (a key fetch, a
    round trip) is paid once for the whole batch. The wire form is base64, so the
    bytes handed over are the decoded ones.
    """
    slots = [slot for site in sites for slot in _payload_slots(wire, site)]
    if not slots:
        return
    payloads: list[bytes] = []
    for slot in slots:
        encoded = slot.container[slot.key]
        if not isinstance(encoded, str):
            raise ValueError(f"payload at {slot.key!r} is not a base64 string")
        payloads.append(base64.b64decode(encoded, validate=True))
    transformed = await transform(payloads)
    if len(transformed) != len(payloads):
        raise ValueError(
            f"codec answered with {len(transformed)} payloads for {len(payloads)}"
        )
    for slot, payload in zip(slots, transformed):
        slot.container[slot.key] = base64.b64encode(payload).decode("ascii")


def _post(url: str, body: bytes, headers: dict[str, str], timeout: float) -> bytes:
    request = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json", **headers},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return typing.cast("bytes", response.read())
    except urllib.error.HTTPError as error:
        detail = error.read().decode(errors="replace")
        raise RuntimeError(f"{url} failed ({error.code}): {detail}") from error


_APPEND_INPUT_PAYLOAD_SITES: tuple[_PayloadSteps, ...] = (
    (
        "payloads",
        None,
    ),
)


_READ_OUTPUT_PAYLOAD_SITES: tuple[_PayloadSteps, ...] = (
    (
        "records",
        None,
        "frame",
    ),
)


class StreamServiceHttpClient:
    """Append records to a workflow's stream and read them back. Reads hand out
    batches and an append carries one batch per call, because a call per record
    costs too much for a token stream.

    Every method posts to `{base_url}/{operation}`, so `base_url` is the service's
    address on the Nexus HTTP ingress, up to but not including the operation name.
    """

    def __init__(
        self,
        base_url: str,
        *,
        codec: PayloadCodec | None = None,
        headers: dict[str, str] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._base_url: str = base_url.rstrip("/")
        self._codec: PayloadCodec | None = codec
        self._headers: dict[str, str] = dict(headers or {})
        self._timeout: float = timeout

    async def append(
        self,
        request: AppendInput,
    ) -> AppendOutput:
        """Append one batch of records. A repeated batchIndex for the same producer
        attempt is dropped, so a retried call writes once.
        """
        wire: typing.Any = _AppendInputTransferTypeConverter().to_transfer_type(request)
        if self._codec is not None:
            await _apply_codec(wire, _APPEND_INPUT_PAYLOAD_SITES, self._codec.encode)
        body = json.dumps(wire).encode()
        raw = await asyncio.to_thread(
            _post,
            f"{self._base_url}/append",
            body,
            self._headers,
            self._timeout,
        )
        answer: typing.Any = json.loads(raw) if raw else {}
        return _AppendOutputTransferTypeConverter().from_transfer_type(
            answer, AppendOutput
        )

    async def read(
        self,
        request: ReadInput,
    ) -> ReadOutput:
        """Answer with the records after the caller's token, or time out. The call
        parks until it has maxRecords records or waitMs elapses, whichever comes
        first, and answers with whatever it collected.
        """
        wire: typing.Any = _ReadInputTransferTypeConverter().to_transfer_type(request)
        body = json.dumps(wire).encode()
        raw = await asyncio.to_thread(
            _post,
            f"{self._base_url}/read",
            body,
            self._headers,
            self._timeout,
        )
        answer: typing.Any = json.loads(raw) if raw else {}
        if self._codec is not None:
            await _apply_codec(answer, _READ_OUTPUT_PAYLOAD_SITES, self._codec.decode)
        return _ReadOutputTransferTypeConverter().from_transfer_type(answer, ReadOutput)

    async def read_until_records(
        self,
        request: ReadInput,
        *,
        deadline: float,
    ) -> ReadOutput:
        """Calls `read` until it answers with something, or until `deadline`.

        Each attempt sets `wait_ms` from the budget left, so the endpoint parks
        for the caller instead of the caller spinning. The first answer whose
        `records` is non-empty is returned. When the deadline passes first, the
        last answer is returned, which still carries the caller's resume position.

        `deadline` is the whole budget in seconds. The single-shot method stays
        available for a caller that wants one attempt.
        """
        end = time.monotonic() + deadline
        while True:
            remaining = end - time.monotonic()
            attempt = dataclasses.replace(
                request, wait_ms=max(1, int(remaining * 1000))
            )
            answer = await self.read(attempt)
            if answer.records:
                return answer
            if time.monotonic() >= end:
                return answer
