# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

import asyncio
import base64
import collections.abc
import dataclasses
import json
import time
import typing
import urllib.error
import urllib.request

from .models import (
    AppendInput,
    AppendOutput,
    ReadInput,
    ReadOutput,
    _AppendInputTransferTypeConverter,
    _AppendOutputTransferTypeConverter,
    _ReadInputTransferTypeConverter,
    _ReadOutputTransferTypeConverter,
)


_PayloadSteps = tuple[str | None, ...]
"""One wire member chain from a model's root to a payload. `None` stands for
every element of the array reached so far.
"""


class _PayloadSite(typing.NamedTuple):
    """One site's step chain and the alphabet its wire string is written in.

    The two base64 alphabets are not interchangeable, so a site carries its own
    rather than the walker assuming one.
    """

    steps: _PayloadSteps
    url_safe: bool


@typing.runtime_checkable
class PayloadCodec(typing.Protocol):
    """Transforms the payload bytes an operation carries.

    A caller applies it before the send and after the receive, so a payload
    never travels in the form the process holds it in. Both directions take and
    answer with a list of the same length, in order.
    """

    async def encode(self, payloads: list[bytes]) -> list[bytes]: ...

    async def decode(self, payloads: list[bytes]) -> list[bytes]: ...


class _Slot(typing.NamedTuple):
    container: typing.Any
    key: typing.Any
    url_safe: bool


def _payload_slots(
    node: typing.Any, steps: _PayloadSteps, url_safe: bool
) -> list[_Slot]:
    if not steps:
        return []
    head, rest = steps[0], steps[1:]
    if head is None:
        if not isinstance(node, list):
            return []
        entries = typing.cast("list[typing.Any]", node)
        if not rest:
            return [_Slot(entries, index, url_safe) for index in range(len(entries))]
        return [
            slot for entry in entries for slot in _payload_slots(entry, rest, url_safe)
        ]
    if not isinstance(node, dict):
        return []
    members = typing.cast("dict[str, typing.Any]", node)
    if head not in members:
        return []
    if not rest:
        return [_Slot(members, head, url_safe)]
    return _payload_slots(members[head], rest, url_safe)


def _decode_payload(encoded: str, url_safe: bool) -> bytes:
    if url_safe:
        # The wire form is unpadded, which `urlsafe_b64decode` will not take.
        return base64.urlsafe_b64decode(encoded + "=" * (-len(encoded) % 4))
    return base64.b64decode(encoded, validate=True)


def _encode_payload(payload: bytes, url_safe: bool) -> str:
    if url_safe:
        return base64.urlsafe_b64encode(payload).decode("ascii").rstrip("=")
    return base64.b64encode(payload).decode("ascii")


async def _apply_codec(
    wire: typing.Any,
    sites: tuple[_PayloadSite, ...],
    transform: collections.abc.Callable[
        [list[bytes]], collections.abc.Awaitable[list[bytes]]
    ],
) -> None:
    """Runs every payload the sites reach through the codec, in one call.

    The codec sees one list per request, so whatever it does (a key fetch, a
    round trip) is paid once for the whole batch. Each site is decoded and
    re-encoded in its own alphabet, so a member the contract wrote as base64url
    goes back on the wire as base64url.
    """
    slots = [
        slot
        for site in sites
        for slot in _payload_slots(wire, site.steps, site.url_safe)
    ]
    if not slots:
        return
    payloads: list[bytes] = []
    for slot in slots:
        encoded = slot.container[slot.key]
        if not isinstance(encoded, str):
            raise ValueError(f"payload at {slot.key!r} is not a base64 string")
        payloads.append(_decode_payload(encoded, slot.url_safe))
    transformed = await transform(payloads)
    if len(transformed) != len(payloads):
        raise ValueError(
            f"codec answered with {len(transformed)} payloads for {len(payloads)}"
        )
    for slot, payload in zip(slots, transformed):
        slot.container[slot.key] = _encode_payload(payload, slot.url_safe)


class HTTPStatusError(RuntimeError):
    """A non-2xx answer from the ingress.

    It carries the status so a caller can tell a refusal apart from an answer
    another attempt could still get.
    """

    def __init__(self, url: str, status: int, detail: str) -> None:
        super().__init__(f"{url} failed ({status}): {detail}")
        self.url = url
        self.status = status
        self.detail = detail

    @property
    def retryable(self) -> bool:
        """Whether the same request could answer differently.

        Too many requests and the server-side failures are the endpoint's own
        transient conditions; every other status is about this request, and
        repeating it changes nothing.
        """
        return self.status == 429 or self.status >= 500


def _post(url: str, body: bytes, headers: dict[str, str], timeout: float) -> bytes:
    request = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json", **headers},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return typing.cast("bytes", response.read())
    except urllib.error.HTTPError as error:
        detail = error.read().decode(errors="replace")
        raise HTTPStatusError(url, error.code, detail) from error


_LONG_POLL_MIN_BACKOFF = 0.05
_LONG_POLL_MAX_BACKOFF = 2.0


async def _long_poll_pause(backoff: float, end: float) -> None:
    """Waits out a backoff without running past the read's own deadline."""
    remaining = end - time.monotonic()
    delay = min(backoff, remaining)
    if delay > 0:
        await asyncio.sleep(delay)


def _long_poll_next_backoff(backoff: float) -> float:
    return min(backoff * 2, _LONG_POLL_MAX_BACKOFF)


_APPEND_INPUT_PAYLOAD_SITES: tuple[_PayloadSite, ...] = (
    _PayloadSite(
        (
            "payloads",
            None,
        ),
        False,
    ),
)


_READ_OUTPUT_PAYLOAD_SITES: tuple[_PayloadSite, ...] = (
    _PayloadSite(
        (
            "records",
            None,
            "frame",
        ),
        False,
    ),
)


class StreamServiceHttpClient:
    """Append records to a workflow's stream and read them back. Reads hand out
    batches and an append carries one batch per call, because a call per record
    costs too much for a token stream.

    Every method posts to `{base_url}/{operation}`, so `base_url` is the service's
    address on the Nexus HTTP ingress, up to but not including the operation name.
    """

    def __init__(
        self,
        base_url: str,
        *,
        codec: PayloadCodec | None = None,
        headers: dict[str, str] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._base_url: str = base_url.rstrip("/")
        self._codec: PayloadCodec | None = codec
        self._headers: dict[str, str] = dict(headers or {})
        self._timeout: float = timeout

    def _poll_budget(self, remaining: float) -> float:
        """How long one attempt may ask the endpoint to park, in seconds.

        Asking for longer than the transport will wait is a socket timeout
        dressed as a long poll, so the ask leaves the answer room to come back
        inside this client's own timeout.
        """
        return max(0.001, min(remaining, self._timeout * 0.9))

    async def append(
        self,
        request: AppendInput,
    ) -> AppendOutput:
        """Append one batch of records. A repeated batchIndex for the same producer
        attempt is dropped, so a retried call writes once.
        """
        wire: typing.Any = _AppendInputTransferTypeConverter().to_transfer_type(request)
        if self._codec is not None:
            await _apply_codec(wire, _APPEND_INPUT_PAYLOAD_SITES, self._codec.encode)
        body = json.dumps(wire).encode()
        raw = await asyncio.to_thread(
            _post,
            f"{self._base_url}/append",
            body,
            self._headers,
            self._timeout,
        )
        if not raw:
            raise ValueError("append answered with an empty body")
        answer: typing.Any = json.loads(raw)
        return _AppendOutputTransferTypeConverter().from_transfer_type(
            answer, AppendOutput
        )

    async def read(
        self,
        request: ReadInput,
    ) -> ReadOutput:
        """Answer with the records after the caller's token, or time out. The call
        parks until it has maxRecords records or waitMs elapses, whichever comes
        first, and answers with whatever it collected.
        """
        wire: typing.Any = _ReadInputTransferTypeConverter().to_transfer_type(request)
        body = json.dumps(wire).encode()
        raw = await asyncio.to_thread(
            _post,
            f"{self._base_url}/read",
            body,
            self._headers,
            self._timeout,
        )
        if not raw:
            raise ValueError("read answered with an empty body")
        answer: typing.Any = json.loads(raw)
        if self._codec is not None:
            await _apply_codec(answer, _READ_OUTPUT_PAYLOAD_SITES, self._codec.decode)
        return _ReadOutputTransferTypeConverter().from_transfer_type(answer, ReadOutput)

    async def read_until_records(
        self,
        request: ReadInput,
        *,
        deadline: float,
    ) -> ReadOutput:
        """Calls `read` until it answers with something, or until `deadline`.

        Each attempt sets `wait_ms` from the budget left, so the endpoint parks
        for the caller instead of the caller spinning. The first answer whose
        `records` is non-empty is returned. When the deadline passes first, the
        last answer is returned, which still carries the caller's resume position.

        `deadline` is the whole budget in seconds. The single-shot method stays
        available for a caller that wants one attempt.
        """
        end = time.monotonic() + deadline
        answer: ReadOutput | None = None
        backoff = _LONG_POLL_MIN_BACKOFF
        while True:
            wait = self._poll_budget(end - time.monotonic())
            attempt = dataclasses.replace(request, wait_ms=int(wait * 1000))
            started = time.monotonic()
            try:
                answer = await self.read(attempt)
            except HTTPStatusError as error:
                if not error.retryable or time.monotonic() >= end:
                    raise
                await _long_poll_pause(backoff, end)
                backoff = _long_poll_next_backoff(backoff)
                continue
            if answer.records:
                return answer
            if time.monotonic() >= end:
                return answer
            if time.monotonic() - started < wait / 2:
                await _long_poll_pause(backoff, end)
                backoff = _long_poll_next_backoff(backoff)
            else:
                backoff = _LONG_POLL_MIN_BACKOFF
