# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing
import typing_extensions
import temporalio.converter
import temporalio.exceptions

from ._definitions import (
    Violation,
    _collect,
    _format_base64,
    _member_path,
    _parse_base64,
    _parse_spec_integer,
    _transfer_type_convertible,
)


StreamCursor = typing.NewType("StreamCursor", str)
"""StreamCursor is an opaque resume token issued by the endpoint.

The value is never parsed, compared or constructed by a caller; only the endpoint that
issued it can interpret it.

Pass one back to resume strictly after the record it names, so that record is never
delivered twice.
"""


class _AppendInputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["AppendInput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["AppendInput"]
    ) -> "AppendInput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        workflow_id_value: str = typing.cast("typing.Any", None)
        if "workflowId" not in raw or raw["workflowId"] is None:
            violations.append(Violation(path="workflowId", reason="required"))
        else:
            workflow_id_value_raw = raw["workflowId"]
            if not isinstance(workflow_id_value_raw, str):
                violations.append(
                    Violation(path="workflowId", reason="expected string")
                )
            else:
                workflow_id_value = workflow_id_value_raw

        stream_value: str = typing.cast("typing.Any", None)
        if "stream" not in raw or raw["stream"] is None:
            violations.append(Violation(path="stream", reason="required"))
        else:
            stream_value_raw = raw["stream"]
            if not isinstance(stream_value_raw, str):
                violations.append(Violation(path="stream", reason="expected string"))
            else:
                stream_value = stream_value_raw

        producer_id_value: str = typing.cast("typing.Any", None)
        if "producerId" not in raw or raw["producerId"] is None:
            violations.append(Violation(path="producerId", reason="required"))
        else:
            producer_id_value_raw = raw["producerId"]
            if not isinstance(producer_id_value_raw, str):
                violations.append(
                    Violation(path="producerId", reason="expected string")
                )
            else:
                producer_id_value = producer_id_value_raw

        attempt_value: int = typing.cast("typing.Any", None)
        if "attempt" not in raw or raw["attempt"] is None:
            violations.append(Violation(path="attempt", reason="required"))
        else:
            attempt_value_raw = raw["attempt"]
            attempt_value_parsed = _parse_spec_integer(
                attempt_value_raw, "attempt", violations
            )
            if attempt_value_parsed is not None:
                attempt_value = attempt_value_parsed
                if attempt_value < 1:
                    violations.append(
                        Violation(
                            path="attempt", reason=f"must be >= 1, got {attempt_value}"
                        )
                    )

        batch_index_value: int = typing.cast("typing.Any", None)
        if "batchIndex" not in raw or raw["batchIndex"] is None:
            violations.append(Violation(path="batchIndex", reason="required"))
        else:
            batch_index_value_raw = raw["batchIndex"]
            batch_index_value_parsed = _parse_spec_integer(
                batch_index_value_raw, "batchIndex", violations
            )
            if batch_index_value_parsed is not None:
                batch_index_value = batch_index_value_parsed
                if batch_index_value < 1:
                    violations.append(
                        Violation(
                            path="batchIndex",
                            reason=f"must be >= 1, got {batch_index_value}",
                        )
                    )

        payloads_value: list[bytes] | None = None
        if "payloads" in raw:
            payloads_value_raw = raw["payloads"]
            if payloads_value_raw is None:
                violations.append(
                    Violation(path="payloads", reason="explicit null not allowed")
                )
            else:
                if not isinstance(payloads_value_raw, list):
                    violations.append(
                        Violation(path="payloads", reason="expected array")
                    )
                else:
                    payloads_value_list: list[bytes] = []
                    for payloads_value_index, payloads_value_element in enumerate(
                        typing.cast("list[typing.Any]", payloads_value_raw)
                    ):
                        payloads_value_item_path = f"payloads[{payloads_value_index}]"
                        payloads_value_item_violation_count = len(violations)
                        payloads_value_item: bytes = typing.cast("typing.Any", None)
                        if not isinstance(payloads_value_element, str):
                            violations.append(
                                Violation(
                                    path=payloads_value_item_path,
                                    reason="expected string",
                                )
                            )
                        else:
                            payloads_value_item_parsed = _parse_base64(
                                payloads_value_element,
                                payloads_value_item_path,
                                violations,
                            )
                            if payloads_value_item_parsed is not None:
                                payloads_value_item = payloads_value_item_parsed
                        if len(violations) == payloads_value_item_violation_count:
                            payloads_value_list.append(payloads_value_item)
                    payloads_value = payloads_value_list

        finish_value: bool | None = None
        if "finish" in raw:
            finish_value_raw = raw["finish"]
            if finish_value_raw is None:
                violations.append(
                    Violation(path="finish", reason="explicit null not allowed")
                )
            else:
                if not isinstance(finish_value_raw, bool):
                    violations.append(
                        Violation(path="finish", reason="expected boolean")
                    )
                else:
                    finish_value = finish_value_raw

        for key in raw:
            if (
                key != "workflowId"
                and key != "stream"
                and key != "producerId"
                and key != "attempt"
                and key != "batchIndex"
                and key != "payloads"
                and key != "finish"
            ):
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return AppendInput(
            workflow_id=workflow_id_value,
            stream=stream_value,
            producer_id=producer_id_value,
            attempt=attempt_value,
            batch_index=batch_index_value,
            payloads=payloads_value,
            finish=finish_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "AppendInput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, AppendInput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        workflow_id_value: typing.Any = runtime_value.workflow_id
        if workflow_id_value is None:
            violations.append(Violation(path="workflowId", reason="required"))
        else:
            if not (isinstance(workflow_id_value, str)):
                violations.append(
                    Violation(path="workflowId", reason="expected string")
                )
            out["workflowId"] = workflow_id_value
        stream_value: typing.Any = runtime_value.stream
        if stream_value is None:
            violations.append(Violation(path="stream", reason="required"))
        else:
            if not (isinstance(stream_value, str)):
                violations.append(Violation(path="stream", reason="expected string"))
            out["stream"] = stream_value
        producer_id_value: typing.Any = runtime_value.producer_id
        if producer_id_value is None:
            violations.append(Violation(path="producerId", reason="required"))
        else:
            if not (isinstance(producer_id_value, str)):
                violations.append(
                    Violation(path="producerId", reason="expected string")
                )
            out["producerId"] = producer_id_value
        attempt_value: typing.Any = runtime_value.attempt
        if attempt_value is None:
            violations.append(Violation(path="attempt", reason="required"))
        else:
            if not (
                not isinstance(attempt_value, bool)
                and (
                    isinstance(attempt_value, int)
                    or (isinstance(attempt_value, float) and attempt_value.is_integer())
                )
            ):
                violations.append(Violation(path="attempt", reason="expected integer"))
            else:
                if abs(attempt_value) > 9007199254740991:
                    violations.append(
                        Violation(
                            path="attempt", reason="exceeds ±(2^53-1) integer cap"
                        )
                    )
                if attempt_value < 1:
                    violations.append(
                        Violation(
                            path="attempt", reason=f"must be >= 1, got {attempt_value}"
                        )
                    )
            out["attempt"] = attempt_value
        batch_index_value: typing.Any = runtime_value.batch_index
        if batch_index_value is None:
            violations.append(Violation(path="batchIndex", reason="required"))
        else:
            if not (
                not isinstance(batch_index_value, bool)
                and (
                    isinstance(batch_index_value, int)
                    or (
                        isinstance(batch_index_value, float)
                        and batch_index_value.is_integer()
                    )
                )
            ):
                violations.append(
                    Violation(path="batchIndex", reason="expected integer")
                )
            else:
                if abs(batch_index_value) > 9007199254740991:
                    violations.append(
                        Violation(
                            path="batchIndex", reason="exceeds ±(2^53-1) integer cap"
                        )
                    )
                if batch_index_value < 1:
                    violations.append(
                        Violation(
                            path="batchIndex",
                            reason=f"must be >= 1, got {batch_index_value}",
                        )
                    )
            out["batchIndex"] = batch_index_value
        payloads_value: typing.Any = runtime_value.payloads
        if payloads_value is not None:
            payloads_violation_count = len(violations)
            if not (isinstance(payloads_value, list)):
                violations.append(Violation(path="payloads", reason="expected array"))
            else:
                checked_array_8 = typing.cast("list[typing.Any]", payloads_value)
                for item_index_8, item_element_8 in enumerate(checked_array_8):
                    if not (isinstance(item_element_8, bytes)):
                        violations.append(
                            Violation(
                                path=f"payloads[{item_index_8}]",
                                reason="expected bytes",
                            )
                        )
            if len(violations) == payloads_violation_count:
                payloads_checked = typing.cast("list[typing.Any]", payloads_value)
                out["payloads"] = [
                    _format_base64(element) for element in payloads_checked
                ]
        finish_value: typing.Any = runtime_value.finish
        if finish_value is not None:
            if not (isinstance(finish_value, bool)):
                violations.append(Violation(path="finish", reason="expected boolean"))
            out["finish"] = finish_value
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_AppendInputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class AppendInput:
    """One append call: who is writing, where, and what."""

    workflow_id: str
    """The workflow whose stream is being written."""

    stream: str
    """The named stream to append to."""

    producer_id: str
    """Identifies the writer across its retries, so its attempts can be ordered."""

    attempt: int
    """The generation this producer is writing. A later attempt supersedes an earlier one."""

    batch_index: int
    """Counts this producer's batches from 1. The handler drops an index it has already
    written for this producer attempt.
    """

    payloads: list[bytes] | None = None
    """The records to write. Empty on a call that only finishes the producer."""

    finish: bool | None = None
    """Mark this producer done after writing the batch, so a reader stops waiting on it."""


class _AppendOutputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["AppendOutput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["AppendOutput"]
    ) -> "AppendOutput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        cursor_value: str | None = None
        if "cursor" in raw:
            cursor_value_raw = raw["cursor"]
            if cursor_value_raw is None:
                violations.append(
                    Violation(path="cursor", reason="explicit null not allowed")
                )
            else:
                if not isinstance(cursor_value_raw, str):
                    violations.append(
                        Violation(path="cursor", reason="expected string")
                    )
                else:
                    cursor_value = cursor_value_raw

        for key in raw:
            if key != "cursor":
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return AppendOutput(
            cursor=cursor_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "AppendOutput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, AppendOutput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        cursor_value: typing.Any = runtime_value.cursor
        if cursor_value is not None:
            if not (isinstance(cursor_value, str)):
                violations.append(Violation(path="cursor", reason="expected string"))
            out["cursor"] = cursor_value
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_AppendOutputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class AppendOutput:
    """Where the append landed, empty when it wrote nothing."""

    cursor: str | None = None
    """Names the last record written by this call. Empty when the call carried no payloads."""


class _ReadInputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["ReadInput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["ReadInput"]
    ) -> "ReadInput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        workflow_id_value: str = typing.cast("typing.Any", None)
        if "workflowId" not in raw or raw["workflowId"] is None:
            violations.append(Violation(path="workflowId", reason="required"))
        else:
            workflow_id_value_raw = raw["workflowId"]
            if not isinstance(workflow_id_value_raw, str):
                violations.append(
                    Violation(path="workflowId", reason="expected string")
                )
            else:
                workflow_id_value = workflow_id_value_raw

        stream_value: str | None = None
        if "stream" in raw:
            stream_value_raw = raw["stream"]
            if stream_value_raw is None:
                violations.append(
                    Violation(path="stream", reason="explicit null not allowed")
                )
            else:
                if not isinstance(stream_value_raw, str):
                    violations.append(
                        Violation(path="stream", reason="expected string")
                    )
                else:
                    stream_value = stream_value_raw

        after_token_value: str | None = None
        if "afterToken" in raw:
            after_token_value_raw = raw["afterToken"]
            if after_token_value_raw is None:
                violations.append(
                    Violation(path="afterToken", reason="explicit null not allowed")
                )
            else:
                if not isinstance(after_token_value_raw, str):
                    violations.append(
                        Violation(path="afterToken", reason="expected string")
                    )
                else:
                    after_token_value = after_token_value_raw

        max_records_value: int | None = None
        if "maxRecords" in raw:
            max_records_value_raw = raw["maxRecords"]
            if max_records_value_raw is None:
                violations.append(
                    Violation(path="maxRecords", reason="explicit null not allowed")
                )
            else:
                max_records_value_parsed = _parse_spec_integer(
                    max_records_value_raw, "maxRecords", violations
                )
                if max_records_value_parsed is not None:
                    max_records_value = max_records_value_parsed
                    if max_records_value < 1:
                        violations.append(
                            Violation(
                                path="maxRecords",
                                reason=f"must be >= 1, got {max_records_value}",
                            )
                        )

        wait_ms_value: int | None = None
        if "waitMs" in raw:
            wait_ms_value_raw = raw["waitMs"]
            if wait_ms_value_raw is None:
                violations.append(
                    Violation(path="waitMs", reason="explicit null not allowed")
                )
            else:
                wait_ms_value_parsed = _parse_spec_integer(
                    wait_ms_value_raw, "waitMs", violations
                )
                if wait_ms_value_parsed is not None:
                    wait_ms_value = wait_ms_value_parsed
                    if wait_ms_value < 0:
                        violations.append(
                            Violation(
                                path="waitMs",
                                reason=f"must be >= 0, got {wait_ms_value}",
                            )
                        )

        for key in raw:
            if (
                key != "workflowId"
                and key != "stream"
                and key != "afterToken"
                and key != "maxRecords"
                and key != "waitMs"
            ):
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return ReadInput(
            workflow_id=workflow_id_value,
            stream=stream_value,
            after_token=after_token_value,
            max_records=max_records_value,
            wait_ms=wait_ms_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "ReadInput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, ReadInput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        workflow_id_value: typing.Any = runtime_value.workflow_id
        if workflow_id_value is None:
            violations.append(Violation(path="workflowId", reason="required"))
        else:
            if not (isinstance(workflow_id_value, str)):
                violations.append(
                    Violation(path="workflowId", reason="expected string")
                )
            out["workflowId"] = workflow_id_value
        stream_value: typing.Any = runtime_value.stream
        if stream_value is not None:
            if not (isinstance(stream_value, str)):
                violations.append(Violation(path="stream", reason="expected string"))
            out["stream"] = stream_value
        after_token_value: typing.Any = runtime_value.after_token
        if after_token_value is not None:
            if not (isinstance(after_token_value, str)):
                violations.append(
                    Violation(path="afterToken", reason="expected string")
                )
            out["afterToken"] = after_token_value
        max_records_value: typing.Any = runtime_value.max_records
        if max_records_value is not None:
            if not (
                not isinstance(max_records_value, bool)
                and (
                    isinstance(max_records_value, int)
                    or (
                        isinstance(max_records_value, float)
                        and max_records_value.is_integer()
                    )
                )
            ):
                violations.append(
                    Violation(path="maxRecords", reason="expected integer")
                )
            else:
                if abs(max_records_value) > 9007199254740991:
                    violations.append(
                        Violation(
                            path="maxRecords", reason="exceeds ±(2^53-1) integer cap"
                        )
                    )
                if max_records_value < 1:
                    violations.append(
                        Violation(
                            path="maxRecords",
                            reason=f"must be >= 1, got {max_records_value}",
                        )
                    )
            out["maxRecords"] = max_records_value
        wait_ms_value: typing.Any = runtime_value.wait_ms
        if wait_ms_value is not None:
            if not (
                not isinstance(wait_ms_value, bool)
                and (
                    isinstance(wait_ms_value, int)
                    or (isinstance(wait_ms_value, float) and wait_ms_value.is_integer())
                )
            ):
                violations.append(Violation(path="waitMs", reason="expected integer"))
            else:
                if abs(wait_ms_value) > 9007199254740991:
                    violations.append(
                        Violation(path="waitMs", reason="exceeds ±(2^53-1) integer cap")
                    )
                if wait_ms_value < 0:
                    violations.append(
                        Violation(
                            path="waitMs", reason=f"must be >= 0, got {wait_ms_value}"
                        )
                    )
            out["waitMs"] = wait_ms_value
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_ReadInputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class ReadInput:
    """One read call: where to resume from and how long to wait."""

    workflow_id: str
    """The workflow whose stream is being read."""

    stream: str | None = None
    """The named stream to read. Empty reads every stream the workflow publishes."""

    after_token: str | None = None
    """A token from an earlier record or append. Empty starts at the beginning."""

    max_records: int | None = None
    """Return at most this many records. Defaults to 100."""

    wait_ms: int | None = None
    """Wait at most this long for records to arrive before answering. Defaults to 5000. A
    call that collects nothing answers with no records and the caller's own token.
    """


class _ReadOutputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["ReadOutput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["ReadOutput"]
    ) -> "ReadOutput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        records_value: list[RecordWire] | None = None
        if "records" in raw:
            records_value_raw = raw["records"]
            if records_value_raw is None:
                violations.append(
                    Violation(path="records", reason="explicit null not allowed")
                )
            else:
                if not isinstance(records_value_raw, list):
                    violations.append(
                        Violation(path="records", reason="expected array")
                    )
                else:
                    records_value_list: list[RecordWire] = []
                    for records_value_index, records_value_element in enumerate(
                        typing.cast("list[typing.Any]", records_value_raw)
                    ):
                        records_value_item_path = f"records[{records_value_index}]"
                        records_value_item_violation_count = len(violations)
                        records_value_item: RecordWire = typing.cast("typing.Any", None)
                        try:
                            records_value_item = (
                                _RecordWireTransferTypeConverter().from_transfer_type(
                                    records_value_element, RecordWire
                                )
                            )
                        except temporalio.exceptions.ApplicationError as error:
                            _collect(violations, records_value_item_path, error)
                        if len(violations) == records_value_item_violation_count:
                            records_value_list.append(records_value_item)
                    records_value = records_value_list

        next_token_value: str | None = None
        if "nextToken" in raw:
            next_token_value_raw = raw["nextToken"]
            if next_token_value_raw is None:
                violations.append(
                    Violation(path="nextToken", reason="explicit null not allowed")
                )
            else:
                if not isinstance(next_token_value_raw, str):
                    violations.append(
                        Violation(path="nextToken", reason="expected string")
                    )
                else:
                    next_token_value = next_token_value_raw

        for key in raw:
            if key != "records" and key != "nextToken":
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return ReadOutput(
            records=records_value,
            next_token=next_token_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "ReadOutput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, ReadOutput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        records_value: typing.Any = runtime_value.records
        if records_value is not None:
            records_violation_count = len(violations)
            if not (isinstance(records_value, list)):
                violations.append(Violation(path="records", reason="expected array"))
            if len(violations) == records_violation_count:
                records_checked = typing.cast("list[typing.Any]", records_value)
                records_out: list[typing.Any] = []
                for records_index, records_element in enumerate(records_checked):
                    try:
                        records_out.append(
                            _RecordWireTransferTypeConverter().to_transfer_type(
                                records_element
                            )
                        )
                    except temporalio.exceptions.ApplicationError as error:
                        _collect(violations, f"records[{records_index}]", error)
                out["records"] = records_out
        next_token_value: typing.Any = runtime_value.next_token
        if next_token_value is not None:
            if not (isinstance(next_token_value, str)):
                violations.append(Violation(path="nextToken", reason="expected string"))
            out["nextToken"] = next_token_value
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_ReadOutputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class ReadOutput:
    """What one read call answered, and where to resume."""

    records: list[RecordWire] | None = None
    """The records after the caller's token, in stream order."""

    next_token: str | None = None
    """Pass as afterToken on the following call. Echoes the caller's own token when the
    call collected nothing.
    """


class _RecordWireTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["RecordWire", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["RecordWire"]
    ) -> "RecordWire":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        token_value: str = typing.cast("typing.Any", None)
        if "token" not in raw or raw["token"] is None:
            violations.append(Violation(path="token", reason="required"))
        else:
            token_value_raw = raw["token"]
            if not isinstance(token_value_raw, str):
                violations.append(Violation(path="token", reason="expected string"))
            else:
                token_value = token_value_raw

        frame_value: bytes = typing.cast("typing.Any", None)
        if "frame" not in raw or raw["frame"] is None:
            violations.append(Violation(path="frame", reason="required"))
        else:
            frame_value_raw = raw["frame"]
            if not isinstance(frame_value_raw, str):
                violations.append(Violation(path="frame", reason="expected string"))
            else:
                frame_value_parsed = _parse_base64(frame_value_raw, "frame", violations)
                if frame_value_parsed is not None:
                    frame_value = frame_value_parsed

        for key in raw:
            if key != "token" and key != "frame":
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return RecordWire(
            token=token_value,
            frame=frame_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "RecordWire") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, RecordWire):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        token_value: typing.Any = runtime_value.token
        if token_value is None:
            violations.append(Violation(path="token", reason="required"))
        else:
            if not (isinstance(token_value, str)):
                violations.append(Violation(path="token", reason="expected string"))
            out["token"] = token_value
        frame_value: typing.Any = runtime_value.frame
        if frame_value is None:
            violations.append(Violation(path="frame", reason="required"))
        else:
            frame_violation_count = len(violations)
            if not (isinstance(frame_value, bytes)):
                violations.append(Violation(path="frame", reason="expected bytes"))
            if len(violations) == frame_violation_count:
                out["frame"] = _format_base64(frame_value)
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_RecordWireTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class RecordWire:
    """One record on the wire: its cursor and its frame."""

    token: str
    """Names this record. Pass it as afterToken to resume just past it."""

    frame: bytes
    """The record frame, carrying the topic, kind, producer, attempt, sequence and body."""
