// Generated by nexgen latest. DO NOT EDIT.
package json_schema.definitions.streams;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.temporal.failure.ApplicationFailure;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * One record on the wire: its cursor and its frame.
 */
@JsonSerialize(using = RecordWire.Serializer.class)
@JsonDeserialize(using = RecordWire.Deserializer.class)
public final class RecordWire {
    private final String token;
    private final byte[] frame;

    public RecordWire(String token, byte[] frame) {
        this.token = token;
        this.frame = frame;
    }

    /**
     * Names this record. Pass it as afterToken to resume just past it.
     */
    public String getToken() {
        return token;
    }

    /**
     * The record frame, carrying the topic, kind, producer, attempt, sequence and body.
     */
    public byte[] getFrame() {
        return frame;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof RecordWire)) {
            return false;
        }
        RecordWire that = (RecordWire) other;
        return Objects.equals(this.token, that.token)
            && java.util.Arrays.equals(this.frame, that.frame);
    }

    @Override
    public int hashCode() {
        return Objects.hash(token, java.util.Arrays.hashCode(frame));
    }

    @Override
    public String toString() {
        return "RecordWire{"
            + "token=" + token
            + ", frame=" + java.util.Arrays.toString(frame)
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<RecordWire> {
        @Override
        public void serialize(RecordWire value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            JsonGenerator target = gen;
            com.fasterxml.jackson.databind.util.TokenBuffer pending = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);
            gen = pending;
            List<Violation> violations = new ArrayList<>();
            if (value.token == null) {
                violations.add(new Violation("token", "required"));
            }
            if (value.frame == null) {
                violations.add(new Violation("frame", "required"));
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            gen.writeStartObject();
            if (value.token != null) {
                gen.writeStringField("token", value.token);
            }
            if (value.frame != null) {
                gen.writeStringField("frame", Base64Support.formatBase64(value.frame));
            }
            gen.writeEndObject();
            pending.serialize(target);
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<RecordWire> {
        @Override
        public RecordWire deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = SpecNumbers.readExactTree(parser);
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                String path = Violation.memberPath(key);
                switch (key) {
                    case "frame":
                    case "token":
                        break;
                    default:
                        violations.add(new Violation(path, "unknown field"));
                }
            }
            String token = null;
            {
                JsonNode field = node.get("token");
                if (field == null) {
                    violations.add(new Violation("token", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("token", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("token", "expected string"));
                    } else {
                        token = field.textValue();
                    }
                }
            }
            byte[] frame = null;
            {
                JsonNode field = node.get("frame");
                if (field == null) {
                    violations.add(new Violation("frame", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("frame", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("frame", "expected string"));
                    } else {
                        frame = Base64Support.parseBase64(field.textValue(), "frame", violations);
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            return new RecordWire(token, frame);
        }
    }
}
