// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import {
  appendInputTransferTypeConverter,
  appendOutputTransferTypeConverter,
  readInputTransferTypeConverter,
  readOutputTransferTypeConverter,
} from "./models";
import type { AppendInput, AppendOutput, ReadInput, ReadOutput } from "./models";

/**
 * Append records to a workflow's stream and read them back. Reads hand out batches and
 * an append carries one batch per call, because a call per record costs too much for a
 * token stream.
 */
export const streamService = nexus.service("example.streams.v1.StreamService", {
  /**
   * Append one batch of records. A repeated batchIndex for the same producer attempt is
   * dropped, so a retried call writes once.
   */
  append: nexus.operation<AppendInput, AppendOutput>({
    name: "append",
    inputType: { transferTypeConverter: appendInputTransferTypeConverter },
    outputType: { transferTypeConverter: appendOutputTransferTypeConverter },
  }),
  /**
   * Answer with the records after the caller's token, or time out. The call parks until
   * it has maxRecords records or waitMs elapses, whichever comes first, and answers
   * with whatever it collected.
   */
  read: nexus.operation<ReadInput, ReadOutput>({
    name: "read",
    inputType: { transferTypeConverter: readInputTransferTypeConverter },
    outputType: { transferTypeConverter: readOutputTransferTypeConverter },
  }),
});
