// Code generated by nexgen latest. DO NOT EDIT.

package streams

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// PayloadCodec transforms the payload bytes an operation carries. A caller
// applies it before the send and after the receive, so a payload never travels
// in the form the process holds it in. Both directions take and answer with a
// slice of the same length, in order.
type PayloadCodec interface {
	Encode(ctx context.Context, payloads [][]byte) ([][]byte, error)
	Decode(ctx context.Context, payloads [][]byte) ([][]byte, error)
}

// payloadStep is one step from a model's root towards a payload: a wire member,
// or every element of the array reached so far.
type payloadStep struct {
	member string
	each   bool
}

// payloadSlot is a place in the decoded request or response body holding one
// payload, addressed so it can be read and written back.
type payloadSlot struct {
	object map[string]any
	key    string
	array  []any
	index  int
}

func (s payloadSlot) get() any {
	if s.object != nil {
		return s.object[s.key]
	}
	return s.array[s.index]
}

func (s payloadSlot) set(value any) {
	if s.object != nil {
		s.object[s.key] = value
		return
	}
	s.array[s.index] = value
}

func collectPayloadSlots(node any, steps []payloadStep, out *[]payloadSlot) {
	if len(steps) == 0 {
		return
	}
	head, rest := steps[0], steps[1:]
	if head.each {
		entries, ok := node.([]any)
		if !ok {
			return
		}
		for index := range entries {
			if len(rest) == 0 {
				*out = append(*out, payloadSlot{array: entries, index: index})
				continue
			}
			collectPayloadSlots(entries[index], rest, out)
		}
		return
	}
	members, ok := node.(map[string]any)
	if !ok {
		return
	}
	if _, present := members[head.member]; !present {
		return
	}
	if len(rest) == 0 {
		*out = append(*out, payloadSlot{object: members, key: head.member})
		return
	}
	collectPayloadSlots(members[head.member], rest, out)
}

// applyPayloadCodec runs every payload the sites reach through transform, in one
// call, and answers with the rewritten body.
//
// The codec sees one slice per request, so whatever it does (a key fetch, a
// round trip) is paid once for the whole batch. The wire form is base64, so the
// bytes handed over are the decoded ones. A body whose sites reach nothing is
// returned untouched, so an operation that happens to carry no payload costs
// nothing beyond the walk.
func applyPayloadCodec(
	ctx context.Context,
	body []byte,
	sites [][]payloadStep,
	transform func(context.Context, [][]byte) ([][]byte, error),
) ([]byte, error) {
	var node any
	if err := json.Unmarshal(body, &node); err != nil {
		return nil, fmt.Errorf("decode body for the payload codec: %w", err)
	}
	var slots []payloadSlot
	for _, site := range sites {
		collectPayloadSlots(node, site, &slots)
	}
	if len(slots) == 0 {
		return body, nil
	}
	payloads := make([][]byte, 0, len(slots))
	for _, slot := range slots {
		encoded, ok := slot.get().(string)
		if !ok {
			return nil, fmt.Errorf("payload at %q is not a base64 string", slot.key)
		}
		decoded, err := base64.StdEncoding.DecodeString(encoded)
		if err != nil {
			return nil, fmt.Errorf("decode payload at %q: %w", slot.key, err)
		}
		payloads = append(payloads, decoded)
	}
	transformed, err := transform(ctx, payloads)
	if err != nil {
		return nil, err
	}
	if len(transformed) != len(payloads) {
		return nil, fmt.Errorf(
			"codec answered with %d payloads for %d", len(transformed), len(payloads),
		)
	}
	for index, slot := range slots {
		slot.set(base64.StdEncoding.EncodeToString(transformed[index]))
	}
	rewritten, err := json.Marshal(node)
	if err != nil {
		return nil, fmt.Errorf("re-encode body after the payload codec: %w", err)
	}
	return rewritten, nil
}

// appendInputPayloadSites addresses every payload the codec owns inside a AppendInput.
var appendInputPayloadSites = [][]payloadStep{
	{{member: "payloads"}, {each: true}},
}

// readOutputPayloadSites addresses every payload the codec owns inside a ReadOutput.
var readOutputPayloadSites = [][]payloadStep{
	{{member: "records"}, {each: true}, {member: "frame"}},
}

// StreamServiceHTTPClient is an HTTP caller for the example.streams.v1.StreamService
// service. Append records to a workflow's stream and read them back. Reads hand out
// batches and an append carries one batch per call, because a call per record costs too
// much for a token stream.
// Every method posts to baseURL/<operation>, so baseURL is the service's address on the
// Nexus HTTP ingress, up to but not including the operation name.
type StreamServiceHTTPClient struct {
	baseURL    string
	httpClient *http.Client
	codec      PayloadCodec
	header     http.Header
}

// StreamServiceHTTPClientOptions configures a StreamServiceHTTPClient. Every member is
// optional.
type StreamServiceHTTPClientOptions struct {
	// HTTPClient issues the requests. A nil value uses http.DefaultClient.
	HTTPClient *http.Client
	// Codec transforms the payloads the operations carry. A nil value passes them through
	// untouched.
	Codec PayloadCodec
	// Header is added to every request.
	Header http.Header
}

// NewStreamServiceHTTPClient constructs a StreamServiceHTTPClient posting to baseURL. A
// nil options is the same as a zero one.
func NewStreamServiceHTTPClient(baseURL string, options *StreamServiceHTTPClientOptions) *StreamServiceHTTPClient {
	if options == nil {
		options = &StreamServiceHTTPClientOptions{}
	}
	httpClient := options.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &StreamServiceHTTPClient{
		baseURL:    strings.TrimRight(baseURL, "/"),
		httpClient: httpClient,
		codec:      options.Codec,
		header:     options.Header,
	}
}

func (c *StreamServiceHTTPClient) post(ctx context.Context, operation string, body []byte) ([]byte, error) {
	url := c.baseURL + "/" + operation
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	for name, values := range c.header {
		for _, value := range values {
			request.Header.Add(name, value)
		}
	}
	request.Header.Set("Content-Type", "application/json")
	response, err := c.httpClient.Do(request)
	if err != nil {
		return nil, err
	}
	defer func() { _ = response.Body.Close() }()
	raw, err := io.ReadAll(response.Body)
	if err != nil {
		return nil, err
	}
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return nil, fmt.Errorf("%s failed (%d): %s", url, response.StatusCode, raw)
	}
	return raw, nil
}

// Append posts one append call. Append one batch of records. A repeated batchIndex for
// the same producer attempt is dropped, so a retried call writes once.
func (c *StreamServiceHTTPClient) Append(ctx context.Context, request AppendInput) (AppendOutput, error) {
	var answer AppendOutput
	body, err := json.Marshal(request)
	if err != nil {
		return answer, err
	}
	if c.codec != nil {
		body, err = applyPayloadCodec(ctx, body, appendInputPayloadSites, c.codec.Encode)
		if err != nil {
			return answer, err
		}
	}
	raw, err := c.post(ctx, "append", body)
	if err != nil {
		return answer, err
	}
	if len(raw) == 0 {
		raw = []byte("{}")
	}
	if err := json.Unmarshal(raw, &answer); err != nil {
		return answer, err
	}
	return answer, nil
}

// Read posts one read call. Answer with the records after the caller's token, or time
// out. The call parks until it has maxRecords records or waitMs elapses, whichever
// comes first, and answers with whatever it collected.
func (c *StreamServiceHTTPClient) Read(ctx context.Context, request ReadInput) (ReadOutput, error) {
	var answer ReadOutput
	body, err := json.Marshal(request)
	if err != nil {
		return answer, err
	}
	raw, err := c.post(ctx, "read", body)
	if err != nil {
		return answer, err
	}
	if len(raw) == 0 {
		raw = []byte("{}")
	}
	if c.codec != nil {
		raw, err = applyPayloadCodec(ctx, raw, readOutputPayloadSites, c.codec.Decode)
		if err != nil {
			return answer, err
		}
	}
	if err := json.Unmarshal(raw, &answer); err != nil {
		return answer, err
	}
	return answer, nil
}

// ReadUntilRecords calls Read until it answers with something, or until the deadline.
// Each attempt sets WaitMs from the budget left, so the endpoint parks for the caller
// instead of the caller spinning. The first answer whose Records is non-empty is
// returned. When the deadline passes first, the last answer is returned, which still
// carries the caller's resume position. The single-shot method stays available for a
// caller that wants one attempt.
func (c *StreamServiceHTTPClient) ReadUntilRecords(ctx context.Context, request ReadInput, deadline time.Duration) (ReadOutput, error) {
	end := time.Now().Add(deadline)
	for {
		wait := time.Until(end).Milliseconds()
		if wait < 1 {
			wait = 1
		}
		attempt := request
		attempt.WaitMs = &wait
		answer, err := c.Read(ctx, attempt)
		if err != nil {
			return answer, err
		}
		if len(answer.Records) > 0 {
			return answer, nil
		}
		if !time.Now().Before(end) {
			return answer, nil
		}
	}
}
