// Generated by nexgen latest. DO NOT EDIT.
package json_schema.api.streams;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.temporal.failure.ApplicationFailure;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * One append call: who is writing, where, and what.
 */
@JsonSerialize(using = AppendInput.Serializer.class)
@JsonDeserialize(using = AppendInput.Deserializer.class)
public final class AppendInput {
    private final String workflowId;
    private final String stream;
    private final String producerId;
    private final long attempt;
    private final long batchIndex;
    private final @Nullable List<byte[]> payloads;
    private final @Nullable Boolean finish;

    public AppendInput(String workflowId, String stream, String producerId, long attempt, long batchIndex, @Nullable List<byte[]> payloads, @Nullable Boolean finish) {
        this.workflowId = workflowId;
        this.stream = stream;
        this.producerId = producerId;
        this.attempt = attempt;
        this.batchIndex = batchIndex;
        this.payloads = payloads;
        this.finish = finish;
    }

    /**
     * The workflow whose stream is being written.
     */
    public String getWorkflowId() {
        return workflowId;
    }

    /**
     * The named stream to append to.
     */
    public String getStream() {
        return stream;
    }

    /**
     * Identifies the writer across its retries, so its attempts can be ordered.
     */
    public String getProducerId() {
        return producerId;
    }

    /**
     * The generation this producer is writing. A later attempt supersedes an earlier
     * one.
     */
    public long getAttempt() {
        return attempt;
    }

    /**
     * Counts this producer's batches from 1. The handler drops an index it has already
     * written for this producer attempt.
     */
    public long getBatchIndex() {
        return batchIndex;
    }

    /**
     * The records to write. Empty on a call that only finishes the producer.
     */
    public @Nullable List<byte[]> getPayloads() {
        return payloads;
    }

    /**
     * Mark this producer done after writing the batch, so a reader stops waiting on it.
     */
    public @Nullable Boolean getFinish() {
        return finish;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof AppendInput)) {
            return false;
        }
        AppendInput that = (AppendInput) other;
        return Objects.equals(this.workflowId, that.workflowId)
            && Objects.equals(this.stream, that.stream)
            && Objects.equals(this.producerId, that.producerId)
            && this.attempt == that.attempt
            && this.batchIndex == that.batchIndex
            && Base64Support.listEquals(this.payloads, that.payloads)
            && Objects.equals(this.finish, that.finish);
    }

    @Override
    public int hashCode() {
        return Objects.hash(workflowId, stream, producerId, attempt, batchIndex, Base64Support.listHashCode(payloads), finish);
    }

    @Override
    public String toString() {
        return "AppendInput{"
            + "workflowId=" + workflowId
            + ", stream=" + stream
            + ", producerId=" + producerId
            + ", attempt=" + attempt
            + ", batchIndex=" + batchIndex
            + ", payloads=" + Base64Support.listToString(payloads)
            + ", finish=" + finish
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<AppendInput> {
        @Override
        public void serialize(AppendInput value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            JsonGenerator target = gen;
            com.fasterxml.jackson.databind.util.TokenBuffer pending = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);
            gen = pending;
            List<Violation> violations = new ArrayList<>();
            if (value.workflowId == null) {
                violations.add(new Violation("workflowId", "required"));
            }
            if (value.stream == null) {
                violations.add(new Violation("stream", "required"));
            }
            if (value.producerId == null) {
                violations.add(new Violation("producerId", "required"));
            }
            {
                if (value.attempt < -SpecNumbers.INTEGER_CAP || value.attempt > SpecNumbers.INTEGER_CAP) {
                    violations.add(new Violation("attempt", "exceeds \u00b1(2^53-1) integer cap"));
                }
                if (value.attempt < 1L) {
                    violations.add(new Violation("attempt", "must be >= 1, got " + value.attempt));
                }
            }
            {
                if (value.batchIndex < -SpecNumbers.INTEGER_CAP || value.batchIndex > SpecNumbers.INTEGER_CAP) {
                    violations.add(new Violation("batchIndex", "exceeds \u00b1(2^53-1) integer cap"));
                }
                if (value.batchIndex < 1L) {
                    violations.add(new Violation("batchIndex", "must be >= 1, got " + value.batchIndex));
                }
            }
            if (value.payloads != null) {
                for (int validationIndex0 = 0; validationIndex0 < value.payloads.size(); validationIndex0++) {
                    byte[] validationValue0 = value.payloads.get(validationIndex0);
                    if (validationValue0 == null) {
                        violations.add(new Violation("payloads" + "[" + validationIndex0 + "]", "explicit null not allowed"));
                    } else {
                        String nestedWire1 = Base64Support.formatBase64(validationValue0);
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            gen.writeStartObject();
            if (value.workflowId != null) {
                gen.writeStringField("workflowId", value.workflowId);
            }
            if (value.stream != null) {
                gen.writeStringField("stream", value.stream);
            }
            if (value.producerId != null) {
                gen.writeStringField("producerId", value.producerId);
            }
            gen.writeNumberField("attempt", value.attempt);

            gen.writeNumberField("batchIndex", value.batchIndex);

            if (value.payloads != null) {
                gen.writeFieldName("payloads");
                gen.writeStartArray();
                for (int wireIndex0 = 0; wireIndex0 < value.payloads.size(); wireIndex0++) {
                    byte @Nullable [] wireElement0 = value.payloads.get(wireIndex0);
                    if (wireElement0 == null) {
                        gen.writeNull();
                    } else {
                        gen.writeString(Base64Support.formatBase64(wireElement0));
                    }
                }
                gen.writeEndArray();
            }
            if (value.finish != null) {
                gen.writeBooleanField("finish", value.finish);
            }
            gen.writeEndObject();
            pending.serialize(target);
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<AppendInput> {
        @Override
        public AppendInput deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = SpecNumbers.readExactTree(parser);
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                String path = Violation.memberPath(key);
                switch (key) {
                    case "attempt":
                    case "batchIndex":
                    case "finish":
                    case "payloads":
                    case "producerId":
                    case "stream":
                    case "workflowId":
                        break;
                    default:
                        violations.add(new Violation(path, "unknown field"));
                }
            }
            String workflowId = null;
            {
                JsonNode field = node.get("workflowId");
                if (field == null) {
                    violations.add(new Violation("workflowId", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("workflowId", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("workflowId", "expected string"));
                    } else {
                        workflowId = field.textValue();
                    }
                }
            }
            String stream = null;
            {
                JsonNode field = node.get("stream");
                if (field == null) {
                    violations.add(new Violation("stream", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("stream", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("stream", "expected string"));
                    } else {
                        stream = field.textValue();
                    }
                }
            }
            String producerId = null;
            {
                JsonNode field = node.get("producerId");
                if (field == null) {
                    violations.add(new Violation("producerId", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("producerId", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("producerId", "expected string"));
                    } else {
                        producerId = field.textValue();
                    }
                }
            }
            long attempt = 0L;
            {
                JsonNode field = node.get("attempt");
                if (field == null) {
                    violations.add(new Violation("attempt", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("attempt", "explicit null not allowed"));
                } else {
                    Long numberValue = SpecNumbers.specLong(field, "attempt", violations);
                    if (numberValue != null) {
                        attempt = numberValue;
                        if (numberValue < 1L) {
                            violations.add(new Violation("attempt", "must be >= 1, got " + numberValue));
                        }
                    }
                }
            }
            long batchIndex = 0L;
            {
                JsonNode field = node.get("batchIndex");
                if (field == null) {
                    violations.add(new Violation("batchIndex", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("batchIndex", "explicit null not allowed"));
                } else {
                    Long numberValue = SpecNumbers.specLong(field, "batchIndex", violations);
                    if (numberValue != null) {
                        batchIndex = numberValue;
                        if (numberValue < 1L) {
                            violations.add(new Violation("batchIndex", "must be >= 1, got " + numberValue));
                        }
                    }
                }
            }
            List<byte[]> payloads = null;
            {
                JsonNode field = node.get("payloads");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("payloads", "explicit null not allowed"));
                } else {
                    if (!field.isArray()) {
                        violations.add(new Violation("payloads", "expected array"));
                    } else {
                        List<byte[]> items = new ArrayList<>();
                        for (int index = 0; index < field.size(); index++) {
                            JsonNode element = field.get(index);
                            String elementPath = "payloads" + "[" + index + "]";
                            if (!element.isTextual()) {
                                violations.add(new Violation(elementPath, "expected string"));
                            } else {
                                byte[] parsed = Base64Support.parseBase64(element.textValue(), elementPath, violations);
                                if (parsed != null) {
                                    items.add(parsed);
                                }
                            }
                        }
                        payloads = items;
                    }
                }
            }
            Boolean finish = null;
            {
                JsonNode field = node.get("finish");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("finish", "explicit null not allowed"));
                } else {
                    if (!field.isBoolean()) {
                        violations.add(new Violation("finish", "expected boolean"));
                    } else {
                        finish = field.booleanValue();
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            return new AppendInput(workflowId, stream, producerId, attempt, batchIndex, payloads, finish);
        }
    }
}
