// Generated by nexgen latest. DO NOT EDIT.
package json_schema.api.streams;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.temporal.failure.ApplicationFailure;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * Where the append landed, empty when it wrote nothing.
 */
@JsonSerialize(using = AppendOutput.Serializer.class)
@JsonDeserialize(using = AppendOutput.Deserializer.class)
public final class AppendOutput {
    private final @Nullable String cursor;

    public AppendOutput(@Nullable String cursor) {
        this.cursor = cursor;
    }

    /**
     * Names the last record written by this call. Empty when the call carried no
     * payloads.
     */
    public @Nullable String getCursor() {
        return cursor;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof AppendOutput)) {
            return false;
        }
        AppendOutput that = (AppendOutput) other;
        return Objects.equals(this.cursor, that.cursor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cursor);
    }

    @Override
    public String toString() {
        return "AppendOutput{"
            + "cursor=" + cursor
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<AppendOutput> {
        @Override
        public void serialize(AppendOutput value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            JsonGenerator target = gen;
            com.fasterxml.jackson.databind.util.TokenBuffer pending = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);
            gen = pending;
            gen.writeStartObject();
            if (value.cursor != null) {
                gen.writeStringField("cursor", value.cursor);
            }
            gen.writeEndObject();
            pending.serialize(target);
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<AppendOutput> {
        @Override
        public AppendOutput deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = SpecNumbers.readExactTree(parser);
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                String path = Violation.memberPath(key);
                switch (key) {
                    case "cursor":
                        break;
                    default:
                        violations.add(new Violation(path, "unknown field"));
                }
            }
            String cursor = null;
            {
                JsonNode field = node.get("cursor");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("cursor", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("cursor", "expected string"));
                    } else {
                        cursor = field.textValue();
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            return new AppendOutput(cursor);
        }
    }
}
