// Generated by nexgen latest. DO NOT EDIT.
package json_schema.api.streams;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.temporal.failure.ApplicationFailure;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * What one read call answered, and where to resume.
 */
@JsonSerialize(using = ReadOutput.Serializer.class)
@JsonDeserialize(using = ReadOutput.Deserializer.class)
public final class ReadOutput {
    private final @Nullable List<RecordWire> records;
    private final @Nullable String nextToken;

    public ReadOutput(@Nullable List<RecordWire> records, @Nullable String nextToken) {
        this.records = records;
        this.nextToken = nextToken;
    }

    /**
     * The records after the caller's token, in stream order.
     */
    public @Nullable List<RecordWire> getRecords() {
        return records;
    }

    /**
     * Pass as afterToken on the following call. Echoes the caller's own token when the
     * call collected nothing.
     */
    public @Nullable String getNextToken() {
        return nextToken;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof ReadOutput)) {
            return false;
        }
        ReadOutput that = (ReadOutput) other;
        return Objects.equals(this.records, that.records)
            && Objects.equals(this.nextToken, that.nextToken);
    }

    @Override
    public int hashCode() {
        return Objects.hash(records, nextToken);
    }

    @Override
    public String toString() {
        return "ReadOutput{"
            + "records=" + records
            + ", nextToken=" + nextToken
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<ReadOutput> {
        @Override
        public void serialize(ReadOutput value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            JsonGenerator target = gen;
            com.fasterxml.jackson.databind.util.TokenBuffer pending = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);
            gen = pending;
            List<Violation> violations = new ArrayList<>();
            if (value.records != null) {
                for (int validationIndex0 = 0; validationIndex0 < value.records.size(); validationIndex0++) {
                    RecordWire validationValue0 = value.records.get(validationIndex0);
                    if (validationValue0 == null) {
                        violations.add(new Violation("records" + "[" + validationIndex0 + "]", "explicit null not allowed"));
                    } else {
                    }
                }
            }
            gen.writeStartObject();
            if (value.records != null) {
                gen.writeFieldName("records");
                gen.writeStartArray();
                for (int nestedIndex0 = 0; nestedIndex0 < value.records.size(); nestedIndex0++) {
                    RecordWire nestedElement0 = value.records.get(nestedIndex0);
                    if (nestedElement0 == null) {
                        gen.writeNull();
                    } else {
                        com.fasterxml.jackson.databind.util.TokenBuffer nestedBuffer1 = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);
                        try {
                            serializers.defaultSerializeValue(nestedElement0, nestedBuffer1);
                            nestedBuffer1.serialize(gen);
                        } catch (ApplicationFailure nested1) {
                            if (!"PayloadValidationError".equals(nested1.getType()) || nested1.getDetails().getSize() == 0) {
                                throw nested1;
                            }
                            // The locally-created failure retains the original list as its first detail.
                            // This unchecked cast is cheap and performs no serialization.
                            @SuppressWarnings("unchecked")
                            List<Violation> nestedViolations1 = (List<Violation>) nested1.getDetails().get(0, List.class);
                            for (Violation nestedViolation1 : nestedViolations1) {
                                violations.add(nestedViolation1.withPathPrefix("records" + "[" + nestedIndex0 + "]"));
                            }
                            gen.writeNull();
                        }
                    }
                }
                gen.writeEndArray();
            }
            if (value.nextToken != null) {
                gen.writeStringField("nextToken", value.nextToken);
            }
            gen.writeEndObject();
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            pending.serialize(target);
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<ReadOutput> {
        @Override
        public ReadOutput deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = SpecNumbers.readExactTree(parser);
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                String path = Violation.memberPath(key);
                switch (key) {
                    case "nextToken":
                    case "records":
                        break;
                    default:
                        violations.add(new Violation(path, "unknown field"));
                }
            }
            List<RecordWire> records = null;
            {
                JsonNode field = node.get("records");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("records", "explicit null not allowed"));
                } else {
                    if (!field.isArray()) {
                        violations.add(new Violation("records", "expected array"));
                    } else {
                        List<RecordWire> items = new ArrayList<>();
                        for (int index = 0; index < field.size(); index++) {
                            JsonNode element = field.get(index);
                            String elementPath = "records" + "[" + index + "]";
                            try {
                                items.add(context.readTreeAsValue(element, RecordWire.class));
                            } catch (ApplicationFailure nested) {
                                if (!"PayloadValidationError".equals(nested.getType()) || nested.getDetails().getSize() == 0) {
                                    throw nested;
                                }
                                // The locally-created failure retains the original list as its first detail.
                                // This unchecked cast is cheap and performs no serialization.
                                @SuppressWarnings("unchecked")
                                List<Violation> nestedViolations = (List<Violation>) nested.getDetails().get(0, List.class);
                                for (Violation violation : nestedViolations) {
                                    violations.add(violation.withPathPrefix(elementPath));
                                }
                            } catch (IOException nested) {
                                violations.add(new Violation(elementPath, nested.getMessage()));
                            }
                        }
                        records = items;
                    }
                }
            }
            String nextToken = null;
            {
                JsonNode field = node.get("nextToken");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("nextToken", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("nextToken", "expected string"));
                    } else {
                        nextToken = field.textValue();
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            return new ReadOutput(records, nextToken);
        }
    }
}
