// Generated by nexgen latest. DO NOT EDIT.
package json_schema.api.streams;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.temporal.failure.ApplicationFailure;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * One read call: where to resume from and how long to wait.
 */
@JsonSerialize(using = ReadInput.Serializer.class)
@JsonDeserialize(using = ReadInput.Deserializer.class)
public final class ReadInput {
    private final String workflowId;
    private final @Nullable String stream;
    private final @Nullable String afterToken;
    private final @Nullable Long maxRecords;
    private final @Nullable Long waitMs;

    public ReadInput(String workflowId, @Nullable String stream, @Nullable String afterToken, @Nullable Long maxRecords, @Nullable Long waitMs) {
        this.workflowId = workflowId;
        this.stream = stream;
        this.afterToken = afterToken;
        this.maxRecords = maxRecords;
        this.waitMs = waitMs;
    }

    /**
     * The workflow whose stream is being read.
     */
    public String getWorkflowId() {
        return workflowId;
    }

    /**
     * The named stream to read. Empty reads every stream the workflow publishes.
     */
    public @Nullable String getStream() {
        return stream;
    }

    /**
     * A token from an earlier record or append. Empty starts at the beginning.
     */
    public @Nullable String getAfterToken() {
        return afterToken;
    }

    /**
     * Return at most this many records. Defaults to 100.
     */
    public @Nullable Long getMaxRecords() {
        return maxRecords;
    }

    /**
     * Wait at most this long for records to arrive before answering. Defaults to 5000.
     * A call that collects nothing answers with no records and the caller's own token.
     */
    public @Nullable Long getWaitMs() {
        return waitMs;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof ReadInput)) {
            return false;
        }
        ReadInput that = (ReadInput) other;
        return Objects.equals(this.workflowId, that.workflowId)
            && Objects.equals(this.stream, that.stream)
            && Objects.equals(this.afterToken, that.afterToken)
            && Objects.equals(this.maxRecords, that.maxRecords)
            && Objects.equals(this.waitMs, that.waitMs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(workflowId, stream, afterToken, maxRecords, waitMs);
    }

    @Override
    public String toString() {
        return "ReadInput{"
            + "workflowId=" + workflowId
            + ", stream=" + stream
            + ", afterToken=" + afterToken
            + ", maxRecords=" + maxRecords
            + ", waitMs=" + waitMs
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<ReadInput> {
        @Override
        public void serialize(ReadInput value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            JsonGenerator target = gen;
            com.fasterxml.jackson.databind.util.TokenBuffer pending = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);
            gen = pending;
            List<Violation> violations = new ArrayList<>();
            if (value.workflowId == null) {
                violations.add(new Violation("workflowId", "required"));
            }
            if (value.maxRecords != null) {
                if (value.maxRecords < -SpecNumbers.INTEGER_CAP || value.maxRecords > SpecNumbers.INTEGER_CAP) {
                    violations.add(new Violation("maxRecords", "exceeds \u00b1(2^53-1) integer cap"));
                }
                if (value.maxRecords < 1L) {
                    violations.add(new Violation("maxRecords", "must be >= 1, got " + value.maxRecords));
                }
            }
            if (value.waitMs != null) {
                if (value.waitMs < -SpecNumbers.INTEGER_CAP || value.waitMs > SpecNumbers.INTEGER_CAP) {
                    violations.add(new Violation("waitMs", "exceeds \u00b1(2^53-1) integer cap"));
                }
                if (value.waitMs < 0L) {
                    violations.add(new Violation("waitMs", "must be >= 0, got " + value.waitMs));
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            gen.writeStartObject();
            if (value.workflowId != null) {
                gen.writeStringField("workflowId", value.workflowId);
            }
            if (value.stream != null) {
                gen.writeStringField("stream", value.stream);
            }
            if (value.afterToken != null) {
                gen.writeStringField("afterToken", value.afterToken);
            }
            if (value.maxRecords != null) {
                gen.writeNumberField("maxRecords", value.maxRecords);
            }
            if (value.waitMs != null) {
                gen.writeNumberField("waitMs", value.waitMs);
            }
            gen.writeEndObject();
            pending.serialize(target);
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<ReadInput> {
        @Override
        public ReadInput deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = SpecNumbers.readExactTree(parser);
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                String path = Violation.memberPath(key);
                switch (key) {
                    case "afterToken":
                    case "maxRecords":
                    case "stream":
                    case "waitMs":
                    case "workflowId":
                        break;
                    default:
                        violations.add(new Violation(path, "unknown field"));
                }
            }
            String workflowId = null;
            {
                JsonNode field = node.get("workflowId");
                if (field == null) {
                    violations.add(new Violation("workflowId", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("workflowId", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("workflowId", "expected string"));
                    } else {
                        workflowId = field.textValue();
                    }
                }
            }
            String stream = null;
            {
                JsonNode field = node.get("stream");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("stream", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("stream", "expected string"));
                    } else {
                        stream = field.textValue();
                    }
                }
            }
            String afterToken = null;
            {
                JsonNode field = node.get("afterToken");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("afterToken", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("afterToken", "expected string"));
                    } else {
                        afterToken = field.textValue();
                    }
                }
            }
            Long maxRecords = null;
            {
                JsonNode field = node.get("maxRecords");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("maxRecords", "explicit null not allowed"));
                } else {
                    Long numberValue = SpecNumbers.specLong(field, "maxRecords", violations);
                    if (numberValue != null) {
                        maxRecords = numberValue;
                        if (numberValue < 1L) {
                            violations.add(new Violation("maxRecords", "must be >= 1, got " + numberValue));
                        }
                    }
                }
            }
            Long waitMs = null;
            {
                JsonNode field = node.get("waitMs");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("waitMs", "explicit null not allowed"));
                } else {
                    Long numberValue = SpecNumbers.specLong(field, "waitMs", violations);
                    if (numberValue != null) {
                        waitMs = numberValue;
                        if (numberValue < 0L) {
                            violations.add(new Violation("waitMs", "must be >= 0, got " + numberValue));
                        }
                    }
                }
            }
            if (!violations.isEmpty()) {
                // TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.
                throw ApplicationFailure.newNonRetryableFailure("Payload validation failed", "PayloadValidationError", violations);
            }
            return new ReadInput(workflowId, stream, afterToken, maxRecords, waitMs);
        }
    }
}
