// Generated by nexgen latest. DO NOT EDIT.
package json_schema.api.streams;

import io.nexusrpc.Operation;
import io.nexusrpc.Service;

/**
 * Append records to a workflow's stream and read them back. Reads hand out batches and
 * an append carries one batch per call, because a call per record costs too much for a
 * token stream.
 */
@Service(name = "example.streams.v1.StreamService")
public interface StreamService {
    /**
     * Append one batch of records. A repeated batchIndex for the same producer attempt
     * is dropped, so a retried call writes once.
     */
    @Operation(name = "append")
    AppendOutput append(AppendInput input);

    /**
     * Answer with the records after the caller's token, or time out. The call parks
     * until it has maxRecords records or waitMs elapses, whichever comes first, and
     * answers with whatever it collected.
     */
    @Operation(name = "read")
    ReadOutput read(ReadInput input);
}
