// Generated by nexgen latest. DO NOT EDIT!

export { firstOperation } from "./operations/first-operation";
export { secondOperation } from "./operations/second-operation";
export type { Request, Response } from "./models";
