// Generated by nexgen latest. DO NOT EDIT!

import { composeInterceptors } from "../../../interceptor-composition";
import type * as nexus from "../../../nexus";
import type { Response, Request } from "./models";

export interface SystemNexusWorkflowOutboundCallsInterceptor {
  firstOperation?: (
    input: Request,
    next: (input: Request) => Promise<nexus.NexusOperationHandle<Response>>,
  ) => Promise<nexus.NexusOperationHandle<Response>>;
  secondOperation?: (
    input: Request,
    next: (input: Request) => Promise<nexus.NexusOperationHandle<Response>>,
  ) => Promise<nexus.NexusOperationHandle<Response>>;
}

/** Dispatches the operation-specific interceptor chain selected by service and operation. */
export function dispatchSystemNexusSpecificInterceptors(
  service: string,
  operation: string,
  interceptors: SystemNexusWorkflowOutboundCallsInterceptor[],
  input: unknown,
  next: <Input, Output>(input: Input) => Promise<nexus.NexusOperationHandle<Output>>,
): Promise<nexus.NexusOperationHandle<unknown>> {
  switch (service) {
    case "InterceptorService":
      switch (operation) {
        case "FirstOperation":
          return composeInterceptors(interceptors, "firstOperation", (request) =>
            next<Request, Response>(request),
          )(input as Request) as Promise<nexus.NexusOperationHandle<unknown>>;
        default:
          return next(input);
      }
    case "InterceptorService":
      switch (operation) {
        case "SecondOperation":
          return composeInterceptors(interceptors, "secondOperation", (request) =>
            next<Request, Response>(request),
          )(input as Request) as Promise<nexus.NexusOperationHandle<unknown>>;
        default:
          return next(input);
      }
    default:
      return next(input);
  }
}
