// Generated by nexgen latest. DO NOT EDIT!

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export interface Response {
  value: string;
}

export interface Request {
  id: string;
}
