// Generated by nexgen latest. DO NOT EDIT!

export const operationRegistry = [
  {
    service: "InterceptorService",
    operation: "FirstOperation",
  },
  {
    service: "InterceptorService",
    operation: "SecondOperation",
  },
] as const;
