// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type { Response, Request } from "./models";

export const interceptorService = nexus.service("InterceptorService", {
  firstOperation: nexus.operation<Request, Response>({ name: "FirstOperation" }),
  secondOperation: nexus.operation<Request, Response>({ name: "SecondOperation" }),
});
