// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Nexgen.InterceptorService
{

    [GeneratedCode("nexgen", null)]
    public record Request
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Request"/> class.
        /// </summary>
        public Request(string id)
        {
            Id = id;
        }

        public string Id { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Response"/> class.
        /// </summary>
        public Response(string value)
        {
            Value = value;
        }

        public string Value { get; init; }
    }

}
