// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System.CodeDom.Compiler;
using System.Threading.Tasks;
using Temporalio.Workflows;

namespace Temporalio.Worker.Interceptors
{

    public partial class WorkflowOutboundInterceptor
    {
        /// <summary>
        /// Intercept the FirstOperation operation.
        /// </summary>
        /// <param name="request">Request for the operation.</param>
        /// <returns>Operation handle.</returns>
        [GeneratedCode("nexgen", null)]
        public virtual Task<NexusWorkflowOperationHandle<Response>> FirstOperationAsync(Request request) => Next.FirstOperationAsync(request);

        /// <summary>
        /// Intercept the SecondOperation operation.
        /// </summary>
        /// <param name="request">Request for the operation.</param>
        /// <returns>Operation handle.</returns>
        [GeneratedCode("nexgen", null)]
        public virtual Task<NexusWorkflowOperationHandle<Response>> SecondOperationAsync(Request request) => Next.SecondOperationAsync(request);

    }

}

namespace Temporalio.Worker
{

    internal partial class WorkflowInstance
    {
        [GeneratedCode("nexgen", null)]
        private Task<NexusWorkflowOperationHandle<TResult>> StartSystemNexusOperationAsync<TResult>(
            string service,
            string operationName,
            object? arg)
        {
            if (service == "InterceptorService" &&
                operationName == "FirstOperation")
            {
                if (arg is not Request request)
                {
                    throw new System.ArgumentException("System Nexus operation expects a Request request.", nameof(arg));
                }
                if (typeof(TResult) != typeof(Response))
                {
                    throw new System.ArgumentException("System Nexus operation expects a Response result.");
                }
                var handle = outbound.Value.FirstOperationAsync(request);
                return (Task<NexusWorkflowOperationHandle<TResult>>)(object)handle;
            }
            if (service == "InterceptorService" &&
                operationName == "SecondOperation")
            {
                if (arg is not Request request)
                {
                    throw new System.ArgumentException("System Nexus operation expects a Request request.", nameof(arg));
                }
                if (typeof(TResult) != typeof(Response))
                {
                    throw new System.ArgumentException("System Nexus operation expects a Response result.");
                }
                var handle = outbound.Value.SecondOperationAsync(request);
                return (Task<NexusWorkflowOperationHandle<TResult>>)(object)handle;
            }
            throw new System.ArgumentException($"Unsupported System Nexus operation: {service}/{operationName}");
        }

        internal partial class OutboundImpl
        {
            [GeneratedCode("nexgen", null)]
            public override Task<NexusWorkflowOperationHandle<Response>> FirstOperationAsync(Request request) => instance.outbound.Value.ScheduleSystemNexusOperationAsync<Response>(new(
                Service: "InterceptorService",
                Operation: new(
                    "FirstOperation",
                    typeof(Request),
                    typeof(Response)),
                Arg: request,
                Headers: null));

            [GeneratedCode("nexgen", null)]
            public override Task<NexusWorkflowOperationHandle<Response>> SecondOperationAsync(Request request) => instance.outbound.Value.ScheduleSystemNexusOperationAsync<Response>(new(
                Service: "InterceptorService",
                Operation: new(
                    "SecondOperation",
                    typeof(Request),
                    typeof(Response)),
                Arg: request,
                Headers: null));

        }
    }
}
