// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "../../../../nexus";
import { interceptorService } from "../services";
import type { Response, Request } from "../models";

/**
 * @param request - Request for the operation.
 */
export async function secondOperation(
  request: Request,
): Promise<nexus.NexusOperationHandle<Response>> {
  const client = nexus.createNexusServiceClient({
    service: interceptorService,
    endpoint: "__temporal_system",
  });
  return await client.startOperation(
    interceptorService.operations.secondOperation,
    request,
  );
}
